;-----------------------------------------------------------------------------
; Menu hierarchy definitions, generated from menusample.txt.
; See menu.asm for the equivalent C struct declaration.
;
; The following symbols are reserved and pre-generated by the compilemenu.py
; script:
;   - mNull
;   - mNullId
;   - mNullName
;   - mNullNameId
;   - mNullHandler
;
; The following symbols are not reserved, but the root menu group is
; recommended to use the 'mRoot' label, which then generates the following
; for the root menu group:
;   - mRoot
;   - mRootId
;   - mRootNameId
;
; The following is the recommended configuration of the 'GroupHandler'
; directive inside a 'MenuConfig':
;   - GroupHandler mGroupHandler
;
; The following are the recommended configurations for a blank menu item:
;   - ItemName mNullName
;   - ItemNameId mNullNameId
;   - ItemHandler mNullHandler
;
; DO NOT EDIT: This file was autogenerated.
;-----------------------------------------------------------------------------

mMenuTableSize equ 37
mMenuTable:
mNull:
mNullId equ 0
    .dw mNullId ; id
    .dw mNullId ; parentId
    .dw mNullNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId
    .dw mNullHandler
    .dw 0
mRoot:
mRootId equ 1
    .dw mRootId ; id
    .dw mNullId ; parentId
    .dw mRootNameId ; nameId
    .db 2 ; numRows
    .dw mMathId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup root: children
; MenuGroup root: children: row 0
mMath:
mMathId equ 2
    .dw mMathId ; id
    .dw mRootId ; parentId
    .dw mMathNameId ; nameId
    .db 1 ; numRows
    .dw mCubeId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mNum:
mNumId equ 3
    .dw mNumId ; id
    .dw mRootId ; parentId
    .dw mNumNameId ; nameId
    .db 1 ; numRows
    .dw mAbsId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mProb:
mProbId equ 4
    .dw mProbId ; id
    .dw mRootId ; parentId
    .dw mProbNameId ; nameId
    .db 1 ; numRows
    .dw mPermId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mBlank005:
mBlank005Id equ 5
    .dw mBlank005Id ; id
    .dw mRootId ; parentId
    .dw mNullNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mHelp:
mHelpId equ 6
    .dw mHelpId ; id
    .dw mRootId ; parentId
    .dw mHelpNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mHelpHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup root: children: row 1
mBase:
mBaseId equ 7
    .dw mBaseId ; id
    .dw mRootId ; parentId
    .dw mBaseNameId ; nameId
    .db 1 ; numRows
    .dw mDecId ; rowBeginId or altNameId
    .dw mBaseHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mMode:
mModeId equ 8
    .dw mModeId ; id
    .dw mRootId ; parentId
    .dw mModeNameId ; nameId
    .db 1 ; numRows
    .dw mFixId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mHyperbolic:
mHyperbolicId equ 9
    .dw mHyperbolicId ; id
    .dw mRootId ; parentId
    .dw mHyperbolicNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mHyperbolicHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mUnit:
mUnitId equ 10
    .dw mUnitId ; id
    .dw mRootId ; parentId
    .dw mUnitNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mUnitHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank011:
mBlank011Id equ 11
    .dw mBlank011Id ; id
    .dw mRootId ; parentId
    .dw mNullNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup MATH: children
; MenuGroup MATH: children: row 0
mCube:
mCubeId equ 12
    .dw mCubeId ; id
    .dw mMathId ; parentId
    .dw mCubeNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mCubeHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCubeRoot:
mCubeRootId equ 13
    .dw mCubeRootId ; id
    .dw mMathId ; parentId
    .dw mCubeRootNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mCubeRootHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mAtan2:
mAtan2Id equ 14
    .dw mAtan2Id ; id
    .dw mMathId ; parentId
    .dw mAtan2NameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mAtan2Handler ; handler (to be implemented)
    .dw 0 ; nameSelector
mPercent:
mPercentId equ 15
    .dw mPercentId ; id
    .dw mMathId ; parentId
    .dw mPercentNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mPercentHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank016:
mBlank016Id equ 16
    .dw mBlank016Id ; id
    .dw mMathId ; parentId
    .dw mNullNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup NUM: children
; MenuGroup NUM: children: row 0
mAbs:
mAbsId equ 17
    .dw mAbsId ; id
    .dw mNumId ; parentId
    .dw mAbsNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mAbsHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mSign:
mSignId equ 18
    .dw mSignId ; id
    .dw mNumId ; parentId
    .dw mSignNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mSignHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mMod:
mModId equ 19
    .dw mModId ; id
    .dw mNumId ; parentId
    .dw mModNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mModHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mLcm:
mLcmId equ 20
    .dw mLcmId ; id
    .dw mNumId ; parentId
    .dw mLcmNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mLcmHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mGcd:
mGcdId equ 21
    .dw mGcdId ; id
    .dw mNumId ; parentId
    .dw mGcdNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mGcdHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup PROB: children
; MenuGroup PROB: children: row 0
mPerm:
mPermId equ 22
    .dw mPermId ; id
    .dw mProbId ; parentId
    .dw mPermNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mPermHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mComb:
mCombId equ 23
    .dw mCombId ; id
    .dw mProbId ; parentId
    .dw mCombNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mCombHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mFactorial:
mFactorialId equ 24
    .dw mFactorialId ; id
    .dw mProbId ; parentId
    .dw mFactorialNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mFactorialHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRandom:
mRandomId equ 25
    .dw mRandomId ; id
    .dw mProbId ; parentId
    .dw mRandomNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mRandomHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRandomSeed:
mRandomSeedId equ 26
    .dw mRandomSeedId ; id
    .dw mProbId ; parentId
    .dw mRandomSeedNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mRandomSeedHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup BASE: children
; MenuGroup BASE: children: row 0
mDec:
mDecId equ 27
    .dw mDecId ; id
    .dw mBaseId ; parentId
    .dw mDecNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mDecHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mHex:
mHexId equ 28
    .dw mHexId ; id
    .dw mBaseId ; parentId
    .dw mHexNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mHexHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mOct:
mOctId equ 29
    .dw mOctId ; id
    .dw mBaseId ; parentId
    .dw mOctNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mOctHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBin:
mBinId equ 30
    .dw mBinId ; id
    .dw mBaseId ; parentId
    .dw mBinNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mBinHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank031:
mBlank031Id equ 31
    .dw mBlank031Id ; id
    .dw mBaseId ; parentId
    .dw mNullNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup MODE: children
; MenuGroup MODE: children: row 0
mFix:
mFixId equ 32
    .dw mFixId ; id
    .dw mModeId ; parentId
    .dw mFixNameId ; nameId
    .db 0 ; numRows
    .dw mFixAltNameId ; rowBeginId or altNameId
    .dw mFixHandler ; handler (to be implemented)
    .dw mFixNameSelector ; nameSelector
mSci:
mSciId equ 33
    .dw mSciId ; id
    .dw mModeId ; parentId
    .dw mSciNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mSciHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mEng:
mEngId equ 34
    .dw mEngId ; id
    .dw mModeId ; parentId
    .dw mEngNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mEngHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRad:
mRadId equ 35
    .dw mRadId ; id
    .dw mModeId ; parentId
    .dw mRadNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mRadHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mDeg:
mDegId equ 36
    .dw mDegId ; id
    .dw mModeId ; parentId
    .dw mDegNameId ; nameId
    .db 0 ; numRows
    .dw 0 ; rowBeginId or altNameId
    .dw mDegHandler ; handler (to be implemented)
    .dw 0 ; nameSelector

; Table of 2-byte pointers to names in the pool of strings below.
mMenuNameTableSize equ 34
mMenuNameTable:
mNullNameId equ 0
    .dw mNullName
mRootNameId equ 1
    .dw mRootName
mMathNameId equ 2
    .dw mMathName
mNumNameId equ 3
    .dw mNumName
mProbNameId equ 4
    .dw mProbName
mHelpNameId equ 5
    .dw mHelpName
mBaseNameId equ 6
    .dw mBaseName
mModeNameId equ 7
    .dw mModeName
mHyperbolicNameId equ 8
    .dw mHyperbolicName
mUnitNameId equ 9
    .dw mUnitName
mCubeNameId equ 10
    .dw mCubeName
mCubeRootNameId equ 11
    .dw mCubeRootName
mAtan2NameId equ 12
    .dw mAtan2Name
mPercentNameId equ 13
    .dw mPercentName
mAbsNameId equ 14
    .dw mAbsName
mSignNameId equ 15
    .dw mSignName
mModNameId equ 16
    .dw mModName
mLcmNameId equ 17
    .dw mLcmName
mGcdNameId equ 18
    .dw mGcdName
mPermNameId equ 19
    .dw mPermName
mCombNameId equ 20
    .dw mCombName
mFactorialNameId equ 21
    .dw mFactorialName
mRandomNameId equ 22
    .dw mRandomName
mRandomSeedNameId equ 23
    .dw mRandomSeedName
mDecNameId equ 24
    .dw mDecName
mHexNameId equ 25
    .dw mHexName
mOctNameId equ 26
    .dw mOctName
mBinNameId equ 27
    .dw mBinName
mFixNameId equ 28
    .dw mFixName
mFixAltNameId equ 29
    .dw mFixAltName
mSciNameId equ 30
    .dw mSciName
mEngNameId equ 31
    .dw mEngName
mRadNameId equ 32
    .dw mRadName
mDegNameId equ 33
    .dw mDegName

; Table of names as NUL terminated C strings.
mNullName:
    .db 0
mRootName:
    .db "root", 0
mMathName:
    .db "MATH", 0
mNumName:
    .db "NUM", 0
mProbName:
    .db "PROB", 0
mHelpName:
    .db "HELP", 0
mBaseName:
    .db "BASE", 0
mModeName:
    .db "MODE", 0
mHyperbolicName:
    .db "HYP", 0
mUnitName:
    .db "UNIT", 0
mCubeName:
    .db Scaret, '3', 0
mCubeRootName:
    .db "CBRT", 0
mAtan2Name:
    .db "ATN2", 0
mPercentName:
    .db Spercent, 0
mAbsName:
    .db "ABS", 0
mSignName:
    .db "SIGN", 0
mModName:
    .db "MOD", 0
mLcmName:
    .db "LCM", 0
mGcdName:
    .db "GCD", 0
mPermName:
    .db "PERM", 0
mCombName:
    .db "COMB", 0
mFactorialName:
    .db 'N', Sexclam, 0
mRandomName:
    .db "RAND", 0
mRandomSeedName:
    .db "SEED", 0
mDecName:
    .db "DEC", 0
mHexName:
    .db "HEX", 0
mOctName:
    .db "OCT", 0
mBinName:
    .db "BIN", 0
mFixName:
    .db "FIX", 0
mFixAltName:
    .db 'F', 'I', 'X', Sblock, 0
mSciName:
    .db "SCI", 0
mEngName:
    .db "ENG", 0
mRadName:
    .db "RAD", 0
mDegName:
    .db "DEG", 0
