;-----------------------------------------------------------------------------
; Unit definitions, generated from unitsample.txt.
; See unit1.asm for the equivalent C struct declaration.
;
; There are 3 sections:
;   - list of unit types
;   - list of units
;   - list of unit names
;
; DO NOT EDIT: This file was autogenerated.
;-----------------------------------------------------------------------------

;-----------------------------------------------------------------------------
; List of unit types.
;-----------------------------------------------------------------------------

unitTypesCount equ 4 ; number of unit types

unitTypeNullType equ 0
unitTypeLength equ 1
unitTypeArea equ 2
unitTypeVolume equ 3

;-----------------------------------------------------------------------------
; List of units.
;-----------------------------------------------------------------------------

unitsCount equ 5 ; number of units
unitInfoTable:

unitNullUnitInfo:
unitNullUnitId equ 0
    .dw unitNullUnitName ; name
    .db unitTypeNullType ; unitType
    .db unitNullUnitId ; baseUnitId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1
unitMeterInfo:
unitMeterId equ 1
    .dw unitMeterName ; name
    .db unitTypeLength ; unitType
    .db unitMeterId ; baseUnitId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1.0
unitFeetInfo:
unitFeetId equ 2
    .dw unitFeetName ; name
    .db unitTypeLength ; unitType
    .db unitMeterId ; baseUnitId
    .db $00, $7F, $30, $48, $00, $00, $00, $00, $00 ; scale=0.3048
unitSqMeterInfo:
unitSqMeterId equ 3
    .dw unitSqMeterName ; name
    .db unitTypeArea ; unitType
    .db unitSqMeterId ; baseUnitId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1.0
unitSqFeetInfo:
unitSqFeetId equ 4
    .dw unitSqFeetName ; name
    .db unitTypeArea ; unitType
    .db unitSqMeterId ; baseUnitId
    .db $00, $7E, $92, $90, $30, $40, $00, $00, $00 ; scale=0.09290304

;-----------------------------------------------------------------------------
; List of unit names.
;-----------------------------------------------------------------------------

unitNamesCount equ 5 ; number of unit names
unitNamesPoolSize equ 51 ; size of unit names string pool

unitNullUnitName:
    .db "nullunit", 0
unitMeterName:
    .db "meter", 0
unitFeetName:
    .db "feet", 0
unitSqMeterName:
    .db 's', 'q', Sspace, 'm', 'e', 't', 'e', 'r', 0
unitSqFeetName:
    .db 's', 'q', Sspace, 'f', 'e', 'e', 't', 0
