;-----------------------------------------------------------------------------
; Unit definitions, generated from unitsample.txt.
; See unit1.asm for the equivalent C struct declaration.
;
; There are 4 sections:
; - list of UnitTypes
; - list of UnitType names
; - list of Units
; - list of Unit names
;
; DO NOT EDIT: This file was autogenerated.
;-----------------------------------------------------------------------------

;-----------------------------------------------------------------------------
; List of UnitTypes.
;-----------------------------------------------------------------------------

unitTypesCount equ 4 ; number of unit types
unitTypeTable:

unitTypeNullTypeInfo:
unitTypeNullTypeId equ 0
    .dw unitTypeNullTypeName ; name
    .db unitNullUnitId ; baseUnit
unitTypeLengthInfo:
unitTypeLengthId equ 1
    .dw unitTypeLengthName ; name
    .db unitMeterId ; baseUnit
unitTypeAreaInfo:
unitTypeAreaId equ 2
    .dw unitTypeAreaName ; name
    .db unitSqMeterId ; baseUnit
unitTypeVolumeInfo:
unitTypeVolumeId equ 3
    .dw unitTypeVolumeName ; name
    .db unitCuMeterId ; baseUnit

;-----------------------------------------------------------------------------
; List of UnitType names.
;-----------------------------------------------------------------------------

unitTypeNamesCount equ 7 ; number of unit type names
unitTypeNamesPoolSize equ 28 ; size of unit type names string pool

unitTypeNullTypeName:
    .db "nulltype", 0
unitTypeLengthName:
    .db "length", 0
unitTypeAreaName:
    .db "area", 0
unitTypeVolumeName:
    .db "volume", 0

;-----------------------------------------------------------------------------
; List of Units.
;-----------------------------------------------------------------------------

unitsCount equ 7 ; number of units
unitTable:

unitNullUnitInfo:
unitNullUnitId equ 0
    .dw unitNullUnitName ; name
    .db unitTypeNullTypeId ; unitTypeId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1
unitMeterInfo:
unitMeterId equ 1
    .dw unitMeterName ; name
    .db unitTypeLengthId ; unitTypeId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1.0
unitFeetInfo:
unitFeetId equ 2
    .dw unitFeetName ; name
    .db unitTypeLengthId ; unitTypeId
    .db $00, $7F, $30, $48, $00, $00, $00, $00, $00 ; scale=0.3048
unitSqMeterInfo:
unitSqMeterId equ 3
    .dw unitSqMeterName ; name
    .db unitTypeAreaId ; unitTypeId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1.0
unitSqFeetInfo:
unitSqFeetId equ 4
    .dw unitSqFeetName ; name
    .db unitTypeAreaId ; unitTypeId
    .db $00, $7E, $92, $90, $30, $40, $00, $00, $00 ; scale=0.09290304
unitCuMeterInfo:
unitCuMeterId equ 5
    .dw unitCuMeterName ; name
    .db unitTypeAreaId ; unitTypeId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1.0
unitCuFeetInfo:
unitCuFeetId equ 6
    .dw unitCuFeetName ; name
    .db unitTypeAreaId ; unitTypeId
    .db $00, $7E, $28, $31, $68, $46, $59, $20, $00 ; scale=0.028316846592

;-----------------------------------------------------------------------------
; List of Unit names.
;-----------------------------------------------------------------------------

unitNamesCount equ 7 ; number of unit names
unitNamesPoolSize equ 54 ; size of unit names string pool

unitNullUnitName:
    .db "nullunit", 0
unitMeterName:
    .db "meter", 0
unitFeetName:
    .db "feet", 0
unitSqMeterName:
    .db 's', 'q', Sspace, 'm', 'e', 't', 'e', 'r', 0
unitSqFeetName:
    .db 's', 'q', Sspace, 'f', 'e', 'e', 't', 0
unitCuMeterName:
    .db 'c', 'u', Sspace, 'm', 'e', 't', 'e', 'r', 0
unitCuFeetName:
    .db 'c', 'u', Sspace, 'f', 'e', 'e', 't', 0
