;-----------------------------------------------------------------------------
; Unit definitions, generated from unitsample.txt.
; See unit1.asm for the equivalent C struct declaration.
;
; There are 3 sections:
;   - list of unit classes
;   - list of units
;   - list of unit names
;
; DO NOT EDIT: This file was autogenerated.
;-----------------------------------------------------------------------------

;-----------------------------------------------------------------------------
; List of unit classes.
;-----------------------------------------------------------------------------

unitClassesCount equ 3 ; number of unit classes

unitClassLength equ 0
unitClassArea equ 1
unitClassVolume equ 2

;-----------------------------------------------------------------------------
; List of units.
;-----------------------------------------------------------------------------

unitsCount equ 4 ; number of units
unitInfoTable:

unitMeterInfo:
unitMeterId equ 0
    .dw unitMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1.0
unitFeetInfo:
unitFeetId equ 1
    .dw unitFeetName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $7F, $30, $48, $00, $00, $00, $00, $00 ; scale=0.3048
unitSqMeterInfo:
unitSqMeterId equ 2
    .dw unitSqMeterName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1.0
unitSqFeetInfo:
unitSqFeetId equ 3
    .dw unitSqFeetName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $7E, $92, $90, $30, $40, $00, $00, $00 ; scale=0.09290304

;-----------------------------------------------------------------------------
; List of unit names.
;-----------------------------------------------------------------------------

unitNamesCount equ 4 ; number of unit names
unitNamesPoolSize equ 42 ; size of unit names string pool

unitMeterName:
    .db "meter", 0
unitFeetName:
    .db "feet", 0
unitSqMeterName:
    .db 's', 'q', Sspace, 'm', 'e', 't', 'e', 'r', 0
unitSqFeetName:
    .db 's', 'q', Sspace, 'f', 'e', 'e', 't', 0
