;-----------------------------------------------------------------------------
; Menu hierarchy definitions, generated from menudef.txt.
; See menu.asm for the equivalent C struct declaration.
;
; The following symbols are reserved and pre-generated by the compilemenu.py
; script:
;   - mNull
;   - mNullId
;   - mNullName
;   - mNullNameId
;   - mNullHandler
;
; The following symbols are not reserved, but the root menu group is
; recommended to use the 'mRoot' label, which then generates the following
; for the root menu group:
;   - mRoot
;   - mRootId
;   - mRootNameId
;
; The following is the recommended configuration of the 'GroupHandler'
; directive inside a 'MenuConfig':
;   - GroupHandler mGroupHandler
;
; The following are the recommended configurations for a blank menu item:
;   - ItemName mNullName
;   - ItemNameId mNullNameId
;   - ItemHandler mNullHandler
;
; DO NOT EDIT: This file was autogenerated.
;-----------------------------------------------------------------------------

mMenuTable:
mNull:
mNullId equ 0
    .db mNullId ; id
    .db mNullId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId
    .dw mNullHandler
    .dw 0
mRoot:
mRootId equ 1
    .db mRootId ; id
    .db mNullId ; parentId
    .db mRootNameId ; nameId
    .db 3 ; numRows
    .db mMathId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup root: children
; MenuGroup root: children: row 0
mMath:
mMathId equ 2
    .db mMathId ; id
    .db mRootId ; parentId
    .db mMathNameId ; nameId
    .db 2 ; numRows
    .db mCubeId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mNum:
mNumId equ 3
    .db mNumId ; id
    .db mRootId ; parentId
    .db mNumNameId ; nameId
    .db 3 ; numRows
    .db mPercentId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mProb:
mProbId equ 4
    .db mProbId ; id
    .db mRootId ; parentId
    .db mProbNameId ; nameId
    .db 1 ; numRows
    .db mCombId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mConv:
mConvId equ 5
    .db mConvId ; id
    .db mRootId ; parentId
    .db mConvNameId ; nameId
    .db 2 ; numRows
    .db mRToDId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mHelp:
mHelpId equ 6
    .db mHelpId ; id
    .db mRootId ; parentId
    .db mHelpNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mHelpHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup root: children: row 1
mBase:
mBaseId equ 7
    .db mBaseId ; id
    .db mRootId ; parentId
    .db mBaseNameId ; nameId
    .db 8 ; numRows
    .db mDecId ; rowBeginId or altNameId
    .dw mBaseHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mHyperbolic:
mHyperbolicId equ 8
    .db mHyperbolicId ; id
    .db mRootId ; parentId
    .db mHyperbolicNameId ; nameId
    .db 2 ; numRows
    .db mBlank097Id ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mStat:
mStatId equ 9
    .db mStatId ; id
    .db mRootId ; parentId
    .db mStatNameId ; nameId
    .db 3 ; numRows
    .db mStatPlusId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mUnit:
mUnitId equ 10
    .db mUnitId ; id
    .db mRootId ; parentId
    .db mUnitNameId ; nameId
    .db 6 ; numRows
    .db mFToCId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mBlank011:
mBlank011Id equ 11
    .db mBlank011Id ; id
    .db mRootId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup root: children: row 2
mClear:
mClearId equ 12
    .db mClearId ; id
    .db mRootId ; parentId
    .db mClearNameId ; nameId
    .db 1 ; numRows
    .db mClearXId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mMode:
mModeId equ 13
    .db mModeId ; id
    .db mRootId ; parentId
    .db mModeNameId ; nameId
    .db 1 ; numRows
    .db mFixId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mStack:
mStackId equ 14
    .db mStackId ; id
    .db mRootId ; parentId
    .db mStackNameId ; nameId
    .db 1 ; numRows
    .db mBlank172Id ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mBlank015:
mBlank015Id equ 15
    .db mBlank015Id ; id
    .db mRootId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mBlank016:
mBlank016Id equ 16
    .db mBlank016Id ; id
    .db mRootId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup MATH: children
; MenuGroup MATH: children: row 0
mCube:
mCubeId equ 17
    .db mCubeId ; id
    .db mMathId ; parentId
    .db mCubeNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCubeHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCubeRoot:
mCubeRootId equ 18
    .db mCubeRootId ; id
    .db mMathId ; parentId
    .db mCubeRootNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCubeRootHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mXRootY:
mXRootYId equ 19
    .db mXRootYId ; id
    .db mMathId ; parentId
    .db mXRootYNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mXRootYHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mAtan2:
mAtan2Id equ 20
    .db mAtan2Id ; id
    .db mMathId ; parentId
    .db mAtan2NameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mAtan2Handler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank021:
mBlank021Id equ 21
    .db mBlank021Id ; id
    .db mMathId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup MATH: children: row 1
mAlog2:
mAlog2Id equ 22
    .db mAlog2Id ; id
    .db mMathId ; parentId
    .db mAlog2NameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mAlog2Handler ; handler (to be implemented)
    .dw 0 ; nameSelector
mLog2:
mLog2Id equ 23
    .db mLog2Id ; id
    .db mMathId ; parentId
    .db mLog2NameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mLog2Handler ; handler (to be implemented)
    .dw 0 ; nameSelector
mLogBase:
mLogBaseId equ 24
    .db mLogBaseId ; id
    .db mMathId ; parentId
    .db mLogBaseNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mLogBaseHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank025:
mBlank025Id equ 25
    .db mBlank025Id ; id
    .db mMathId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mBlank026:
mBlank026Id equ 26
    .db mBlank026Id ; id
    .db mMathId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup NUM: children
; MenuGroup NUM: children: row 0
mPercent:
mPercentId equ 27
    .db mPercentId ; id
    .db mNumId ; parentId
    .db mPercentNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mPercentHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mPercentChange:
mPercentChangeId equ 28
    .db mPercentChangeId ; id
    .db mNumId ; parentId
    .db mPercentChangeNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mPercentChangeHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mGcd:
mGcdId equ 29
    .db mGcdId ; id
    .db mNumId ; parentId
    .db mGcdNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mGcdHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mLcm:
mLcmId equ 30
    .db mLcmId ; id
    .db mNumId ; parentId
    .db mLcmNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mLcmHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mPrime:
mPrimeId equ 31
    .db mPrimeId ; id
    .db mNumId ; parentId
    .db mPrimeNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mPrimeHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup NUM: children: row 1
mIntPart:
mIntPartId equ 32
    .db mIntPartId ; id
    .db mNumId ; parentId
    .db mIntPartNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mIntPartHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mFracPart:
mFracPartId equ 33
    .db mFracPartId ; id
    .db mNumId ; parentId
    .db mFracPartNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mFracPartHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mFloor:
mFloorId equ 34
    .db mFloorId ; id
    .db mNumId ; parentId
    .db mFloorNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mFloorHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCeil:
mCeilId equ 35
    .db mCeilId ; id
    .db mNumId ; parentId
    .db mCeilNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCeilHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mNear:
mNearId equ 36
    .db mNearId ; id
    .db mNumId ; parentId
    .db mNearNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNearHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup NUM: children: row 2
mAbs:
mAbsId equ 37
    .db mAbsId ; id
    .db mNumId ; parentId
    .db mAbsNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mAbsHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mSign:
mSignId equ 38
    .db mSignId ; id
    .db mNumId ; parentId
    .db mSignNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mSignHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mMod:
mModId equ 39
    .db mModId ; id
    .db mNumId ; parentId
    .db mModNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mModHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mMin:
mMinId equ 40
    .db mMinId ; id
    .db mNumId ; parentId
    .db mMinNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mMinHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mMax:
mMaxId equ 41
    .db mMaxId ; id
    .db mNumId ; parentId
    .db mMaxNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mMaxHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup PROB: children
; MenuGroup PROB: children: row 0
mComb:
mCombId equ 42
    .db mCombId ; id
    .db mProbId ; parentId
    .db mCombNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCombHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mPerm:
mPermId equ 43
    .db mPermId ; id
    .db mProbId ; parentId
    .db mPermNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mPermHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mFactorial:
mFactorialId equ 44
    .db mFactorialId ; id
    .db mProbId ; parentId
    .db mFactorialNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mFactorialHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRandom:
mRandomId equ 45
    .db mRandomId ; id
    .db mProbId ; parentId
    .db mRandomNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRandomHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRandomSeed:
mRandomSeedId equ 46
    .db mRandomSeedId ; id
    .db mProbId ; parentId
    .db mRandomSeedNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRandomSeedHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup CONV: children
; MenuGroup CONV: children: row 0
mRToD:
mRToDId equ 47
    .db mRToDId ; id
    .db mConvId ; parentId
    .db mRToDNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRToDHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mDToR:
mDToRId equ 48
    .db mDToRId ; id
    .db mConvId ; parentId
    .db mDToRNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mDToRHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank049:
mBlank049Id equ 49
    .db mBlank049Id ; id
    .db mConvId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mPToR:
mPToRId equ 50
    .db mPToRId ; id
    .db mConvId ; parentId
    .db mPToRNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mPToRHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRToP:
mRToPId equ 51
    .db mRToPId ; id
    .db mConvId ; parentId
    .db mRToPNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRToPHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup CONV: children: row 1
mHmsToHr:
mHmsToHrId equ 52
    .db mHmsToHrId ; id
    .db mConvId ; parentId
    .db mHmsToHrNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mHmsToHrHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mHrToHms:
mHrToHmsId equ 53
    .db mHrToHmsId ; id
    .db mConvId ; parentId
    .db mHrToHmsNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mHrToHmsHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank054:
mBlank054Id equ 54
    .db mBlank054Id ; id
    .db mConvId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mBlank055:
mBlank055Id equ 55
    .db mBlank055Id ; id
    .db mConvId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mBlank056:
mBlank056Id equ 56
    .db mBlank056Id ; id
    .db mConvId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup BASE: children
; MenuGroup BASE: children: row 0
mDec:
mDecId equ 57
    .db mDecId ; id
    .db mBaseId ; parentId
    .db mDecNameId ; nameId
    .db 0 ; numRows
    .db mDecAltNameId ; rowBeginId or altNameId
    .dw mDecHandler ; handler (to be implemented)
    .dw mDecNameSelector ; nameSelector
mHex:
mHexId equ 58
    .db mHexId ; id
    .db mBaseId ; parentId
    .db mHexNameId ; nameId
    .db 0 ; numRows
    .db mHexAltNameId ; rowBeginId or altNameId
    .dw mHexHandler ; handler (to be implemented)
    .dw mHexNameSelector ; nameSelector
mOct:
mOctId equ 59
    .db mOctId ; id
    .db mBaseId ; parentId
    .db mOctNameId ; nameId
    .db 0 ; numRows
    .db mOctAltNameId ; rowBeginId or altNameId
    .dw mOctHandler ; handler (to be implemented)
    .dw mOctNameSelector ; nameSelector
mBin:
mBinId equ 60
    .db mBinId ; id
    .db mBaseId ; parentId
    .db mBinNameId ; nameId
    .db 0 ; numRows
    .db mBinAltNameId ; rowBeginId or altNameId
    .dw mBinHandler ; handler (to be implemented)
    .dw mBinNameSelector ; nameSelector
mBlank061:
mBlank061Id equ 61
    .db mBlank061Id ; id
    .db mBaseId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup BASE: children: row 1
mBitwiseAnd:
mBitwiseAndId equ 62
    .db mBitwiseAndId ; id
    .db mBaseId ; parentId
    .db mBitwiseAndNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseAndHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseOr:
mBitwiseOrId equ 63
    .db mBitwiseOrId ; id
    .db mBaseId ; parentId
    .db mBitwiseOrNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseOrHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseXor:
mBitwiseXorId equ 64
    .db mBitwiseXorId ; id
    .db mBaseId ; parentId
    .db mBitwiseXorNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseXorHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseNot:
mBitwiseNotId equ 65
    .db mBitwiseNotId ; id
    .db mBaseId ; parentId
    .db mBitwiseNotNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseNotHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseNeg:
mBitwiseNegId equ 66
    .db mBitwiseNegId ; id
    .db mBaseId ; parentId
    .db mBitwiseNegNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseNegHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup BASE: children: row 2
mShiftLeftLogical:
mShiftLeftLogicalId equ 67
    .db mShiftLeftLogicalId ; id
    .db mBaseId ; parentId
    .db mShiftLeftLogicalNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mShiftLeftLogicalHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mShiftRightLogical:
mShiftRightLogicalId equ 68
    .db mShiftRightLogicalId ; id
    .db mBaseId ; parentId
    .db mShiftRightLogicalNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mShiftRightLogicalHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mShiftRightArithmetic:
mShiftRightArithmeticId equ 69
    .db mShiftRightArithmeticId ; id
    .db mBaseId ; parentId
    .db mShiftRightArithmeticNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mShiftRightArithmeticHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mShiftLeftLogicalN:
mShiftLeftLogicalNId equ 70
    .db mShiftLeftLogicalNId ; id
    .db mBaseId ; parentId
    .db mShiftLeftLogicalNNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mShiftLeftLogicalNHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mShiftRightLogicalN:
mShiftRightLogicalNId equ 71
    .db mShiftRightLogicalNId ; id
    .db mBaseId ; parentId
    .db mShiftRightLogicalNNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mShiftRightLogicalNHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup BASE: children: row 3
mRotateLeftCircular:
mRotateLeftCircularId equ 72
    .db mRotateLeftCircularId ; id
    .db mBaseId ; parentId
    .db mRotateLeftCircularNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRotateLeftCircularHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRotateRightCircular:
mRotateRightCircularId equ 73
    .db mRotateRightCircularId ; id
    .db mBaseId ; parentId
    .db mRotateRightCircularNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRotateRightCircularHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRotateLeftCarry:
mRotateLeftCarryId equ 74
    .db mRotateLeftCarryId ; id
    .db mBaseId ; parentId
    .db mRotateLeftCarryNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRotateLeftCarryHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRotateRightCarry:
mRotateRightCarryId equ 75
    .db mRotateRightCarryId ; id
    .db mBaseId ; parentId
    .db mRotateRightCarryNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRotateRightCarryHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank076:
mBlank076Id equ 76
    .db mBlank076Id ; id
    .db mBaseId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup BASE: children: row 4
mRotateLeftCircularN:
mRotateLeftCircularNId equ 77
    .db mRotateLeftCircularNId ; id
    .db mBaseId ; parentId
    .db mRotateLeftCircularNNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRotateLeftCircularNHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRotateRightCircularN:
mRotateRightCircularNId equ 78
    .db mRotateRightCircularNId ; id
    .db mBaseId ; parentId
    .db mRotateRightCircularNNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRotateRightCircularNHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRotateLeftCarryN:
mRotateLeftCarryNId equ 79
    .db mRotateLeftCarryNId ; id
    .db mBaseId ; parentId
    .db mRotateLeftCarryNNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRotateLeftCarryNHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRotateRightCarryN:
mRotateRightCarryNId equ 80
    .db mRotateRightCarryNId ; id
    .db mBaseId ; parentId
    .db mRotateRightCarryNNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRotateRightCarryNHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank081:
mBlank081Id equ 81
    .db mBlank081Id ; id
    .db mBaseId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup BASE: children: row 5
mClearBit:
mClearBitId equ 82
    .db mClearBitId ; id
    .db mBaseId ; parentId
    .db mClearBitNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mClearBitHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mSetBit:
mSetBitId equ 83
    .db mSetBitId ; id
    .db mBaseId ; parentId
    .db mSetBitNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mSetBitHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mGetBit:
mGetBitId equ 84
    .db mGetBitId ; id
    .db mBaseId ; parentId
    .db mGetBitNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mGetBitHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mReverseBit:
mReverseBitId equ 85
    .db mReverseBitId ; id
    .db mBaseId ; parentId
    .db mReverseBitNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mReverseBitHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCountBit:
mCountBitId equ 86
    .db mCountBitId ; id
    .db mBaseId ; parentId
    .db mCountBitNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCountBitHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup BASE: children: row 6
mBitwiseAdd:
mBitwiseAddId equ 87
    .db mBitwiseAddId ; id
    .db mBaseId ; parentId
    .db mBitwiseAddNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseAddHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseSubt:
mBitwiseSubtId equ 88
    .db mBitwiseSubtId ; id
    .db mBaseId ; parentId
    .db mBitwiseSubtNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseSubtHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseMult:
mBitwiseMultId equ 89
    .db mBitwiseMultId ; id
    .db mBaseId ; parentId
    .db mBitwiseMultNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseMultHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseDiv:
mBitwiseDivId equ 90
    .db mBitwiseDivId ; id
    .db mBaseId ; parentId
    .db mBitwiseDivNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseDivHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseDiv2:
mBitwiseDiv2Id equ 91
    .db mBitwiseDiv2Id ; id
    .db mBaseId ; parentId
    .db mBitwiseDiv2NameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseDiv2Handler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup BASE: children: row 7
mClearCarryFlag:
mClearCarryFlagId equ 92
    .db mClearCarryFlagId ; id
    .db mBaseId ; parentId
    .db mClearCarryFlagNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mClearCarryFlagHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mSetCarryFlag:
mSetCarryFlagId equ 93
    .db mSetCarryFlagId ; id
    .db mBaseId ; parentId
    .db mSetCarryFlagNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mSetCarryFlagHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mGetCarryFlag:
mGetCarryFlagId equ 94
    .db mGetCarryFlagId ; id
    .db mBaseId ; parentId
    .db mGetCarryFlagNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mGetCarryFlagHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mSetWordSize:
mSetWordSizeId equ 95
    .db mSetWordSizeId ; id
    .db mBaseId ; parentId
    .db mSetWordSizeNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mSetWordSizeHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mGetWordSize:
mGetWordSizeId equ 96
    .db mGetWordSizeId ; id
    .db mBaseId ; parentId
    .db mGetWordSizeNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mGetWordSizeHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup HYP: children
; MenuGroup HYP: children: row 0
mBlank097:
mBlank097Id equ 97
    .db mBlank097Id ; id
    .db mHyperbolicId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mSinh:
mSinhId equ 98
    .db mSinhId ; id
    .db mHyperbolicId ; parentId
    .db mSinhNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mSinhHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCosh:
mCoshId equ 99
    .db mCoshId ; id
    .db mHyperbolicId ; parentId
    .db mCoshNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCoshHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mTanh:
mTanhId equ 100
    .db mTanhId ; id
    .db mHyperbolicId ; parentId
    .db mTanhNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mTanhHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank101:
mBlank101Id equ 101
    .db mBlank101Id ; id
    .db mHyperbolicId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup HYP: children: row 1
mBlank102:
mBlank102Id equ 102
    .db mBlank102Id ; id
    .db mHyperbolicId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mAsinh:
mAsinhId equ 103
    .db mAsinhId ; id
    .db mHyperbolicId ; parentId
    .db mAsinhNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mAsinhHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mAcosh:
mAcoshId equ 104
    .db mAcoshId ; id
    .db mHyperbolicId ; parentId
    .db mAcoshNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mAcoshHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mAtanh:
mAtanhId equ 105
    .db mAtanhId ; id
    .db mHyperbolicId ; parentId
    .db mAtanhNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mAtanhHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank106:
mBlank106Id equ 106
    .db mBlank106Id ; id
    .db mHyperbolicId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup STAT: children
; MenuGroup STAT: children: row 0
mStatPlus:
mStatPlusId equ 107
    .db mStatPlusId ; id
    .db mStatId ; parentId
    .db mStatPlusNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatPlusHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatMinus:
mStatMinusId equ 108
    .db mStatMinusId ; id
    .db mStatId ; parentId
    .db mStatMinusNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatMinusHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatAllMode:
mStatAllModeId equ 109
    .db mStatAllModeId ; id
    .db mStatId ; parentId
    .db mStatAllModeNameId ; nameId
    .db 0 ; numRows
    .db mStatAllModeAltNameId ; rowBeginId or altNameId
    .dw mStatAllModeHandler ; handler (to be implemented)
    .dw mStatAllModeNameSelector ; nameSelector
mStatLinearMode:
mStatLinearModeId equ 110
    .db mStatLinearModeId ; id
    .db mStatId ; parentId
    .db mStatLinearModeNameId ; nameId
    .db 0 ; numRows
    .db mStatLinearModeAltNameId ; rowBeginId or altNameId
    .dw mStatLinearModeHandler ; handler (to be implemented)
    .dw mStatLinearModeNameSelector ; nameSelector
mStatClear:
mStatClearId equ 111
    .db mStatClearId ; id
    .db mStatId ; parentId
    .db mStatClearNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatClearHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup STAT: children: row 1
mStatSum:
mStatSumId equ 112
    .db mStatSumId ; id
    .db mStatId ; parentId
    .db mStatSumNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatSumHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatMean:
mStatMeanId equ 113
    .db mStatMeanId ; id
    .db mStatId ; parentId
    .db mStatMeanNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatMeanHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatWeightedMean:
mStatWeightedMeanId equ 114
    .db mStatWeightedMeanId ; id
    .db mStatId ; parentId
    .db mStatWeightedMeanNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatWeightedMeanHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatN:
mStatNId equ 115
    .db mStatNId ; id
    .db mStatId ; parentId
    .db mStatNNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatNHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank116:
mBlank116Id equ 116
    .db mBlank116Id ; id
    .db mStatId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup STAT: children: row 2
mStatSampleSdev:
mStatSampleSdevId equ 117
    .db mStatSampleSdevId ; id
    .db mStatId ; parentId
    .db mStatSampleSdevNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatSampleSdevHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatSampleCov:
mStatSampleCovId equ 118
    .db mStatSampleCovId ; id
    .db mStatId ; parentId
    .db mStatSampleCovNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatSampleCovHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatPopSdev:
mStatPopSdevId equ 119
    .db mStatPopSdevId ; id
    .db mStatId ; parentId
    .db mStatPopSdevNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatPopSdevHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatPopCov:
mStatPopCovId equ 120
    .db mStatPopCovId ; id
    .db mStatId ; parentId
    .db mStatPopCovNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatPopCovHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCfit:
mCfitId equ 121
    .db mCfitId ; id
    .db mStatId ; parentId
    .db mCfitNameId ; nameId
    .db 2 ; numRows
    .db mCfitForcastXId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup CFIT: children
; MenuGroup CFIT: children: row 0
mCfitForcastX:
mCfitForcastXId equ 122
    .db mCfitForcastXId ; id
    .db mCfitId ; parentId
    .db mCfitForcastXNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCfitForcastXHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCfitForcastY:
mCfitForcastYId equ 123
    .db mCfitForcastYId ; id
    .db mCfitId ; parentId
    .db mCfitForcastYNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCfitForcastYHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCfitSlope:
mCfitSlopeId equ 124
    .db mCfitSlopeId ; id
    .db mCfitId ; parentId
    .db mCfitSlopeNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCfitSlopeHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCfitIntercept:
mCfitInterceptId equ 125
    .db mCfitInterceptId ; id
    .db mCfitId ; parentId
    .db mCfitInterceptNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCfitInterceptHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCfitCorrelation:
mCfitCorrelationId equ 126
    .db mCfitCorrelationId ; id
    .db mCfitId ; parentId
    .db mCfitCorrelationNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCfitCorrelationHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup CFIT: children: row 1
mCfitLinear:
mCfitLinearId equ 127
    .db mCfitLinearId ; id
    .db mCfitId ; parentId
    .db mCfitLinearNameId ; nameId
    .db 0 ; numRows
    .db mCfitLinearAltNameId ; rowBeginId or altNameId
    .dw mCfitLinearHandler ; handler (to be implemented)
    .dw mCfitLinearNameSelector ; nameSelector
mCfitLog:
mCfitLogId equ 128
    .db mCfitLogId ; id
    .db mCfitId ; parentId
    .db mCfitLogNameId ; nameId
    .db 0 ; numRows
    .db mCfitLogAltNameId ; rowBeginId or altNameId
    .dw mCfitLogHandler ; handler (to be implemented)
    .dw mCfitLogNameSelector ; nameSelector
mCfitExp:
mCfitExpId equ 129
    .db mCfitExpId ; id
    .db mCfitId ; parentId
    .db mCfitExpNameId ; nameId
    .db 0 ; numRows
    .db mCfitExpAltNameId ; rowBeginId or altNameId
    .dw mCfitExpHandler ; handler (to be implemented)
    .dw mCfitExpNameSelector ; nameSelector
mCfitPower:
mCfitPowerId equ 130
    .db mCfitPowerId ; id
    .db mCfitId ; parentId
    .db mCfitPowerNameId ; nameId
    .db 0 ; numRows
    .db mCfitPowerAltNameId ; rowBeginId or altNameId
    .dw mCfitPowerHandler ; handler (to be implemented)
    .dw mCfitPowerNameSelector ; nameSelector
mCfitBest:
mCfitBestId equ 131
    .db mCfitBestId ; id
    .db mCfitId ; parentId
    .db mCfitBestNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCfitBestHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup UNIT: children
; MenuGroup UNIT: children: row 0
mFToC:
mFToCId equ 132
    .db mFToCId ; id
    .db mUnitId ; parentId
    .db mFToCNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mFToCHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCToF:
mCToFId equ 133
    .db mCToFId ; id
    .db mUnitId ; parentId
    .db mCToFNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCToFHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank134:
mBlank134Id equ 134
    .db mBlank134Id ; id
    .db mUnitId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mInhgToHpa:
mInhgToHpaId equ 135
    .db mInhgToHpaId ; id
    .db mUnitId ; parentId
    .db mInhgToHpaNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mInhgToHpaHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mHpaToInhg:
mHpaToInhgId equ 136
    .db mHpaToInhgId ; id
    .db mUnitId ; parentId
    .db mHpaToInhgNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mHpaToInhgHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup UNIT: children: row 1
mMiToKm:
mMiToKmId equ 137
    .db mMiToKmId ; id
    .db mUnitId ; parentId
    .db mMiToKmNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mMiToKmHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mKmToMi:
mKmToMiId equ 138
    .db mKmToMiId ; id
    .db mUnitId ; parentId
    .db mKmToMiNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mKmToMiHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank139:
mBlank139Id equ 139
    .db mBlank139Id ; id
    .db mUnitId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mFtToM:
mFtToMId equ 140
    .db mFtToMId ; id
    .db mUnitId ; parentId
    .db mFtToMNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mFtToMHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mMToFt:
mMToFtId equ 141
    .db mMToFtId ; id
    .db mUnitId ; parentId
    .db mMToFtNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mMToFtHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup UNIT: children: row 2
mInToCm:
mInToCmId equ 142
    .db mInToCmId ; id
    .db mUnitId ; parentId
    .db mInToCmNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mInToCmHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCmToIn:
mCmToInId equ 143
    .db mCmToInId ; id
    .db mUnitId ; parentId
    .db mCmToInNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCmToInHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank144:
mBlank144Id equ 144
    .db mBlank144Id ; id
    .db mUnitId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mMilToMicron:
mMilToMicronId equ 145
    .db mMilToMicronId ; id
    .db mUnitId ; parentId
    .db mMilToMicronNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mMilToMicronHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mMicronToMil:
mMicronToMilId equ 146
    .db mMicronToMilId ; id
    .db mUnitId ; parentId
    .db mMicronToMilNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mMicronToMilHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup UNIT: children: row 3
mLbsToKg:
mLbsToKgId equ 147
    .db mLbsToKgId ; id
    .db mUnitId ; parentId
    .db mLbsToKgNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mLbsToKgHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mKgToLbs:
mKgToLbsId equ 148
    .db mKgToLbsId ; id
    .db mUnitId ; parentId
    .db mKgToLbsNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mKgToLbsHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank149:
mBlank149Id equ 149
    .db mBlank149Id ; id
    .db mUnitId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mOzToG:
mOzToGId equ 150
    .db mOzToGId ; id
    .db mUnitId ; parentId
    .db mOzToGNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mOzToGHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mGToOz:
mGToOzId equ 151
    .db mGToOzId ; id
    .db mUnitId ; parentId
    .db mGToOzNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mGToOzHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup UNIT: children: row 4
mGalToL:
mGalToLId equ 152
    .db mGalToLId ; id
    .db mUnitId ; parentId
    .db mGalToLNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mGalToLHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mLToGal:
mLToGalId equ 153
    .db mLToGalId ; id
    .db mUnitId ; parentId
    .db mLToGalNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mLToGalHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank154:
mBlank154Id equ 154
    .db mBlank154Id ; id
    .db mUnitId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mFlozToMl:
mFlozToMlId equ 155
    .db mFlozToMlId ; id
    .db mUnitId ; parentId
    .db mFlozToMlNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mFlozToMlHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mMlToFloz:
mMlToFlozId equ 156
    .db mMlToFlozId ; id
    .db mUnitId ; parentId
    .db mMlToFlozNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mMlToFlozHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup UNIT: children: row 5
mCalToKj:
mCalToKjId equ 157
    .db mCalToKjId ; id
    .db mUnitId ; parentId
    .db mCalToKjNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCalToKjHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mKjToCal:
mKjToCalId equ 158
    .db mKjToCalId ; id
    .db mUnitId ; parentId
    .db mKjToCalNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mKjToCalHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank159:
mBlank159Id equ 159
    .db mBlank159Id ; id
    .db mUnitId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mHpToKw:
mHpToKwId equ 160
    .db mHpToKwId ; id
    .db mUnitId ; parentId
    .db mHpToKwNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mHpToKwHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mKwToHp:
mKwToHpId equ 161
    .db mKwToHpId ; id
    .db mUnitId ; parentId
    .db mKwToHpNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mKwToHpHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup CLR: children
; MenuGroup CLR: children: row 0
mClearX:
mClearXId equ 162
    .db mClearXId ; id
    .db mClearId ; parentId
    .db mClearXNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mClearXHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mClearStack:
mClearStackId equ 163
    .db mClearStackId ; id
    .db mClearId ; parentId
    .db mClearStackNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mClearStackHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mClearRegs:
mClearRegsId equ 164
    .db mClearRegsId ; id
    .db mClearId ; parentId
    .db mClearRegsNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mClearRegsHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mClearStat:
mClearStatId equ 165
    .db mClearStatId ; id
    .db mClearId ; parentId
    .db mClearStatNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mClearStatHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank166:
mBlank166Id equ 166
    .db mBlank166Id ; id
    .db mClearId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup MODE: children
; MenuGroup MODE: children: row 0
mFix:
mFixId equ 167
    .db mFixId ; id
    .db mModeId ; parentId
    .db mFixNameId ; nameId
    .db 0 ; numRows
    .db mFixAltNameId ; rowBeginId or altNameId
    .dw mFixHandler ; handler (to be implemented)
    .dw mFixNameSelector ; nameSelector
mSci:
mSciId equ 168
    .db mSciId ; id
    .db mModeId ; parentId
    .db mSciNameId ; nameId
    .db 0 ; numRows
    .db mSciAltNameId ; rowBeginId or altNameId
    .dw mSciHandler ; handler (to be implemented)
    .dw mSciNameSelector ; nameSelector
mEng:
mEngId equ 169
    .db mEngId ; id
    .db mModeId ; parentId
    .db mEngNameId ; nameId
    .db 0 ; numRows
    .db mEngAltNameId ; rowBeginId or altNameId
    .dw mEngHandler ; handler (to be implemented)
    .dw mEngNameSelector ; nameSelector
mRad:
mRadId equ 170
    .db mRadId ; id
    .db mModeId ; parentId
    .db mRadNameId ; nameId
    .db 0 ; numRows
    .db mRadAltNameId ; rowBeginId or altNameId
    .dw mRadHandler ; handler (to be implemented)
    .dw mRadNameSelector ; nameSelector
mDeg:
mDegId equ 171
    .db mDegId ; id
    .db mModeId ; parentId
    .db mDegNameId ; nameId
    .db 0 ; numRows
    .db mDegAltNameId ; rowBeginId or altNameId
    .dw mDegHandler ; handler (to be implemented)
    .dw mDegNameSelector ; nameSelector
; MenuGroup STK: children
; MenuGroup STK: children: row 0
mBlank172:
mBlank172Id equ 172
    .db mBlank172Id ; id
    .db mStackId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mStackRotUp:
mStackRotUpId equ 173
    .db mStackRotUpId ; id
    .db mStackId ; parentId
    .db mStackRotUpNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStackRotUpHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStackRotDown:
mStackRotDownId equ 174
    .db mStackRotDownId ; id
    .db mStackId ; parentId
    .db mStackRotDownNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStackRotDownHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStackExchangeXY:
mStackExchangeXYId equ 175
    .db mStackExchangeXYId ; id
    .db mStackId ; parentId
    .db mStackExchangeXYNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStackExchangeXYHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank176:
mBlank176Id equ 176
    .db mBlank176Id ; id
    .db mStackId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector

; Table of 2-byte pointers to names in the pool of strings below.
mMenuNameTable:
mNullNameId equ 0
    .dw mNullName
mRootNameId equ 1
    .dw mRootName
mMathNameId equ 2
    .dw mMathName
mNumNameId equ 3
    .dw mNumName
mProbNameId equ 4
    .dw mProbName
mConvNameId equ 5
    .dw mConvName
mHelpNameId equ 6
    .dw mHelpName
mBaseNameId equ 7
    .dw mBaseName
mHyperbolicNameId equ 8
    .dw mHyperbolicName
mStatNameId equ 9
    .dw mStatName
mUnitNameId equ 10
    .dw mUnitName
mClearNameId equ 11
    .dw mClearName
mModeNameId equ 12
    .dw mModeName
mStackNameId equ 13
    .dw mStackName
mCubeNameId equ 14
    .dw mCubeName
mCubeRootNameId equ 15
    .dw mCubeRootName
mXRootYNameId equ 16
    .dw mXRootYName
mAtan2NameId equ 17
    .dw mAtan2Name
mAlog2NameId equ 18
    .dw mAlog2Name
mLog2NameId equ 19
    .dw mLog2Name
mLogBaseNameId equ 20
    .dw mLogBaseName
mPercentNameId equ 21
    .dw mPercentName
mPercentChangeNameId equ 22
    .dw mPercentChangeName
mGcdNameId equ 23
    .dw mGcdName
mLcmNameId equ 24
    .dw mLcmName
mPrimeNameId equ 25
    .dw mPrimeName
mIntPartNameId equ 26
    .dw mIntPartName
mFracPartNameId equ 27
    .dw mFracPartName
mFloorNameId equ 28
    .dw mFloorName
mCeilNameId equ 29
    .dw mCeilName
mNearNameId equ 30
    .dw mNearName
mAbsNameId equ 31
    .dw mAbsName
mSignNameId equ 32
    .dw mSignName
mModNameId equ 33
    .dw mModName
mMinNameId equ 34
    .dw mMinName
mMaxNameId equ 35
    .dw mMaxName
mCombNameId equ 36
    .dw mCombName
mPermNameId equ 37
    .dw mPermName
mFactorialNameId equ 38
    .dw mFactorialName
mRandomNameId equ 39
    .dw mRandomName
mRandomSeedNameId equ 40
    .dw mRandomSeedName
mRToDNameId equ 41
    .dw mRToDName
mDToRNameId equ 42
    .dw mDToRName
mPToRNameId equ 43
    .dw mPToRName
mRToPNameId equ 44
    .dw mRToPName
mHmsToHrNameId equ 45
    .dw mHmsToHrName
mHrToHmsNameId equ 46
    .dw mHrToHmsName
mDecNameId equ 47
    .dw mDecName
mDecAltNameId equ 48
    .dw mDecAltName
mHexNameId equ 49
    .dw mHexName
mHexAltNameId equ 50
    .dw mHexAltName
mOctNameId equ 51
    .dw mOctName
mOctAltNameId equ 52
    .dw mOctAltName
mBinNameId equ 53
    .dw mBinName
mBinAltNameId equ 54
    .dw mBinAltName
mBitwiseAndNameId equ 55
    .dw mBitwiseAndName
mBitwiseOrNameId equ 56
    .dw mBitwiseOrName
mBitwiseXorNameId equ 57
    .dw mBitwiseXorName
mBitwiseNotNameId equ 58
    .dw mBitwiseNotName
mBitwiseNegNameId equ 59
    .dw mBitwiseNegName
mShiftLeftLogicalNameId equ 60
    .dw mShiftLeftLogicalName
mShiftRightLogicalNameId equ 61
    .dw mShiftRightLogicalName
mShiftRightArithmeticNameId equ 62
    .dw mShiftRightArithmeticName
mShiftLeftLogicalNNameId equ 63
    .dw mShiftLeftLogicalNName
mShiftRightLogicalNNameId equ 64
    .dw mShiftRightLogicalNName
mRotateLeftCircularNameId equ 65
    .dw mRotateLeftCircularName
mRotateRightCircularNameId equ 66
    .dw mRotateRightCircularName
mRotateLeftCarryNameId equ 67
    .dw mRotateLeftCarryName
mRotateRightCarryNameId equ 68
    .dw mRotateRightCarryName
mRotateLeftCircularNNameId equ 69
    .dw mRotateLeftCircularNName
mRotateRightCircularNNameId equ 70
    .dw mRotateRightCircularNName
mRotateLeftCarryNNameId equ 71
    .dw mRotateLeftCarryNName
mRotateRightCarryNNameId equ 72
    .dw mRotateRightCarryNName
mClearBitNameId equ 73
    .dw mClearBitName
mSetBitNameId equ 74
    .dw mSetBitName
mGetBitNameId equ 75
    .dw mGetBitName
mReverseBitNameId equ 76
    .dw mReverseBitName
mCountBitNameId equ 77
    .dw mCountBitName
mBitwiseAddNameId equ 78
    .dw mBitwiseAddName
mBitwiseSubtNameId equ 79
    .dw mBitwiseSubtName
mBitwiseMultNameId equ 80
    .dw mBitwiseMultName
mBitwiseDivNameId equ 81
    .dw mBitwiseDivName
mBitwiseDiv2NameId equ 82
    .dw mBitwiseDiv2Name
mClearCarryFlagNameId equ 83
    .dw mClearCarryFlagName
mSetCarryFlagNameId equ 84
    .dw mSetCarryFlagName
mGetCarryFlagNameId equ 85
    .dw mGetCarryFlagName
mSetWordSizeNameId equ 86
    .dw mSetWordSizeName
mGetWordSizeNameId equ 87
    .dw mGetWordSizeName
mSinhNameId equ 88
    .dw mSinhName
mCoshNameId equ 89
    .dw mCoshName
mTanhNameId equ 90
    .dw mTanhName
mAsinhNameId equ 91
    .dw mAsinhName
mAcoshNameId equ 92
    .dw mAcoshName
mAtanhNameId equ 93
    .dw mAtanhName
mStatPlusNameId equ 94
    .dw mStatPlusName
mStatMinusNameId equ 95
    .dw mStatMinusName
mStatAllModeNameId equ 96
    .dw mStatAllModeName
mStatAllModeAltNameId equ 97
    .dw mStatAllModeAltName
mStatLinearModeNameId equ 98
    .dw mStatLinearModeName
mStatLinearModeAltNameId equ 99
    .dw mStatLinearModeAltName
mStatClearNameId equ 100
    .dw mStatClearName
mStatSumNameId equ 101
    .dw mStatSumName
mStatMeanNameId equ 102
    .dw mStatMeanName
mStatWeightedMeanNameId equ 103
    .dw mStatWeightedMeanName
mStatNNameId equ 104
    .dw mStatNName
mStatSampleSdevNameId equ 105
    .dw mStatSampleSdevName
mStatSampleCovNameId equ 106
    .dw mStatSampleCovName
mStatPopSdevNameId equ 107
    .dw mStatPopSdevName
mStatPopCovNameId equ 108
    .dw mStatPopCovName
mCfitNameId equ 109
    .dw mCfitName
mCfitForcastXNameId equ 110
    .dw mCfitForcastXName
mCfitForcastYNameId equ 111
    .dw mCfitForcastYName
mCfitSlopeNameId equ 112
    .dw mCfitSlopeName
mCfitInterceptNameId equ 113
    .dw mCfitInterceptName
mCfitCorrelationNameId equ 114
    .dw mCfitCorrelationName
mCfitLinearNameId equ 115
    .dw mCfitLinearName
mCfitLinearAltNameId equ 116
    .dw mCfitLinearAltName
mCfitLogNameId equ 117
    .dw mCfitLogName
mCfitLogAltNameId equ 118
    .dw mCfitLogAltName
mCfitExpNameId equ 119
    .dw mCfitExpName
mCfitExpAltNameId equ 120
    .dw mCfitExpAltName
mCfitPowerNameId equ 121
    .dw mCfitPowerName
mCfitPowerAltNameId equ 122
    .dw mCfitPowerAltName
mCfitBestNameId equ 123
    .dw mCfitBestName
mFToCNameId equ 124
    .dw mFToCName
mCToFNameId equ 125
    .dw mCToFName
mInhgToHpaNameId equ 126
    .dw mInhgToHpaName
mHpaToInhgNameId equ 127
    .dw mHpaToInhgName
mMiToKmNameId equ 128
    .dw mMiToKmName
mKmToMiNameId equ 129
    .dw mKmToMiName
mFtToMNameId equ 130
    .dw mFtToMName
mMToFtNameId equ 131
    .dw mMToFtName
mInToCmNameId equ 132
    .dw mInToCmName
mCmToInNameId equ 133
    .dw mCmToInName
mMilToMicronNameId equ 134
    .dw mMilToMicronName
mMicronToMilNameId equ 135
    .dw mMicronToMilName
mLbsToKgNameId equ 136
    .dw mLbsToKgName
mKgToLbsNameId equ 137
    .dw mKgToLbsName
mOzToGNameId equ 138
    .dw mOzToGName
mGToOzNameId equ 139
    .dw mGToOzName
mGalToLNameId equ 140
    .dw mGalToLName
mLToGalNameId equ 141
    .dw mLToGalName
mFlozToMlNameId equ 142
    .dw mFlozToMlName
mMlToFlozNameId equ 143
    .dw mMlToFlozName
mCalToKjNameId equ 144
    .dw mCalToKjName
mKjToCalNameId equ 145
    .dw mKjToCalName
mHpToKwNameId equ 146
    .dw mHpToKwName
mKwToHpNameId equ 147
    .dw mKwToHpName
mClearXNameId equ 148
    .dw mClearXName
mClearStackNameId equ 149
    .dw mClearStackName
mClearRegsNameId equ 150
    .dw mClearRegsName
mClearStatNameId equ 151
    .dw mClearStatName
mFixNameId equ 152
    .dw mFixName
mFixAltNameId equ 153
    .dw mFixAltName
mSciNameId equ 154
    .dw mSciName
mSciAltNameId equ 155
    .dw mSciAltName
mEngNameId equ 156
    .dw mEngName
mEngAltNameId equ 157
    .dw mEngAltName
mRadNameId equ 158
    .dw mRadName
mRadAltNameId equ 159
    .dw mRadAltName
mDegNameId equ 160
    .dw mDegName
mDegAltNameId equ 161
    .dw mDegAltName
mStackRotUpNameId equ 162
    .dw mStackRotUpName
mStackRotDownNameId equ 163
    .dw mStackRotDownName
mStackExchangeXYNameId equ 164
    .dw mStackExchangeXYName

; Table of names as NUL terminated C strings.
mNullName:
    .db 0
mRootName:
    .db "root", 0
mMathName:
    .db "MATH", 0
mNumName:
    .db "NUM", 0
mProbName:
    .db "PROB", 0
mConvName:
    .db "CONV", 0
mHelpName:
    .db "HELP", 0
mBaseName:
    .db "BASE", 0
mHyperbolicName:
    .db "HYP", 0
mStatName:
    .db "STAT", 0
mUnitName:
    .db "UNIT", 0
mClearName:
    .db "CLR", 0
mModeName:
    .db "MODE", 0
mStackName:
    .db "STK", 0
mCubeName:
    .db 'X', Scaret, '3', 0
mCubeRootName:
    .db ScubeR, Sroot, 'X', 0
mXRootYName:
    .db 'X', Sroot, 'Y', 0
mAtan2Name:
    .db "ATN2", 0
mAlog2Name:
    .db '2', Scaret, 'X', 0
mLog2Name:
    .db "LOG2", 0
mLogBaseName:
    .db "LOGB", 0
mPercentName:
    .db Spercent, 0
mPercentChangeName:
    .db Spercent, 'C', 'H', 0
mGcdName:
    .db "GCD", 0
mLcmName:
    .db "LCM", 0
mPrimeName:
    .db "PRIM", 0
mIntPartName:
    .db "IP", 0
mFracPartName:
    .db "FP", 0
mFloorName:
    .db "FLR", 0
mCeilName:
    .db "CEIL", 0
mNearName:
    .db "NEAR", 0
mAbsName:
    .db "ABS", 0
mSignName:
    .db "SIGN", 0
mModName:
    .db "MOD", 0
mMinName:
    .db "MIN", 0
mMaxName:
    .db "MAX", 0
mCombName:
    .db "COMB", 0
mPermName:
    .db "PERM", 0
mFactorialName:
    .db 'N', Sexclam, 0
mRandomName:
    .db "RAND", 0
mRandomSeedName:
    .db "SEED", 0
mRToDName:
    .db Sconvert, 'D', 'E', 'G', 0
mDToRName:
    .db Sconvert, 'R', 'A', 'D', 0
mPToRName:
    .db Sconvert, 'R', 'E', 'C', 0
mRToPName:
    .db Sconvert, 'P', 'O', 'L', 0
mHmsToHrName:
    .db Sconvert, 'H', 'R', 0
mHrToHmsName:
    .db Sconvert, 'H', 'M', 'S', 0
mDecName:
    .db "DEC", 0
mDecAltName:
    .db 'D', 'E', 'C', Sblock, 0
mHexName:
    .db "HEX", 0
mHexAltName:
    .db 'H', 'E', 'X', Sblock, 0
mOctName:
    .db "OCT", 0
mOctAltName:
    .db 'O', 'C', 'T', Sblock, 0
mBinName:
    .db "BIN", 0
mBinAltName:
    .db 'B', 'I', 'N', Sblock, 0
mBitwiseAndName:
    .db "AND", 0
mBitwiseOrName:
    .db "OR", 0
mBitwiseXorName:
    .db "XOR", 0
mBitwiseNotName:
    .db "NOT", 0
mBitwiseNegName:
    .db "NEG", 0
mShiftLeftLogicalName:
    .db "SL", 0
mShiftRightLogicalName:
    .db "SR", 0
mShiftRightArithmeticName:
    .db "ASR", 0
mShiftLeftLogicalNName:
    .db "SLn", 0
mShiftRightLogicalNName:
    .db "SRn", 0
mRotateLeftCircularName:
    .db "RL", 0
mRotateRightCircularName:
    .db "RR", 0
mRotateLeftCarryName:
    .db "RLC", 0
mRotateRightCarryName:
    .db "RRC", 0
mRotateLeftCircularNName:
    .db "RLn", 0
mRotateRightCircularNName:
    .db "RRn", 0
mRotateLeftCarryNName:
    .db "RLCn", 0
mRotateRightCarryNName:
    .db "RRCn", 0
mClearBitName:
    .db "CB", 0
mSetBitName:
    .db "SB", 0
mGetBitName:
    .db 'B', Squestion, 0
mReverseBitName:
    .db "REVB", 0
mCountBitName:
    .db "CNTB", 0
mBitwiseAddName:
    .db 'B', SplusSign, 0
mBitwiseSubtName:
    .db 'B', Sdash, 0
mBitwiseMultName:
    .db 'B', Scross, 0
mBitwiseDivName:
    .db 'B', Sslash, 0
mBitwiseDiv2Name:
    .db "BDIV", 0
mClearCarryFlagName:
    .db "CCF", 0
mSetCarryFlagName:
    .db "SCF", 0
mGetCarryFlagName:
    .db 'C', 'F', Squestion, 0
mSetWordSizeName:
    .db "WSIZ", 0
mGetWordSizeName:
    .db 'W', 'S', 'Z', Squestion, 0
mSinhName:
    .db "SINH", 0
mCoshName:
    .db "COSH", 0
mTanhName:
    .db "TANH", 0
mAsinhName:
    .db "ASNH", 0
mAcoshName:
    .db "ACSH", 0
mAtanhName:
    .db "ATNH", 0
mStatPlusName:
    .db ScapSigma, SplusSign, 0
mStatMinusName:
    .db ScapSigma, Sdash, 0
mStatAllModeName:
    .db 'A', 'L', 'L', ScapSigma, 0
mStatAllModeAltName:
    .db 'A', 'L', 'L', Sblock, 0
mStatLinearModeName:
    .db 'L', 'I', 'N', ScapSigma, 0
mStatLinearModeAltName:
    .db 'L', 'I', 'N', Sblock, 0
mStatClearName:
    .db 'C', 'L', ScapSigma, 0
mStatSumName:
    .db "SUM", 0
mStatMeanName:
    .db "MEAN", 0
mStatWeightedMeanName:
    .db "WMN", 0
mStatNName:
    .db "N", 0
mStatSampleSdevName:
    .db "SDEV", 0
mStatSampleCovName:
    .db "SCOV", 0
mStatPopSdevName:
    .db "PDEV", 0
mStatPopCovName:
    .db "PCOV", 0
mCfitName:
    .db "CFIT", 0
mCfitForcastXName:
    .db 'Y', Sconvert, 'X', 0
mCfitForcastYName:
    .db 'X', Sconvert, 'Y', 0
mCfitSlopeName:
    .db "SLOP", 0
mCfitInterceptName:
    .db "YINT", 0
mCfitCorrelationName:
    .db "CORR", 0
mCfitLinearName:
    .db "LINF", 0
mCfitLinearAltName:
    .db 'L', 'I', 'N', Sblock, 0
mCfitLogName:
    .db "LOGF", 0
mCfitLogAltName:
    .db 'L', 'O', 'G', Sblock, 0
mCfitExpName:
    .db "EXPF", 0
mCfitExpAltName:
    .db 'E', 'X', 'P', Sblock, 0
mCfitPowerName:
    .db "PWRF", 0
mCfitPowerAltName:
    .db 'P', 'W', 'R', Sblock, 0
mCfitBestName:
    .db "BEST", 0
mFToCName:
    .db Sconvert, Stemp, 'C', 0
mCToFName:
    .db Sconvert, Stemp, 'F', 0
mInhgToHpaName:
    .db Sconvert, 'h', 'P', 'a', 0
mHpaToInhgName:
    .db Sconvert, 'i', 'H', 'g', 0
mMiToKmName:
    .db Sconvert, 'k', 'm', 0
mKmToMiName:
    .db Sconvert, 'm', 'i', 0
mFtToMName:
    .db Sconvert, 'm', 0
mMToFtName:
    .db Sconvert, 'f', 't', 0
mInToCmName:
    .db Sconvert, 'c', 'm', 0
mCmToInName:
    .db Sconvert, 'i', 'n', 0
mMilToMicronName:
    .db Sconvert, Smu, 'm', 0
mMicronToMilName:
    .db Sconvert, 'm', 'i', 'l', 0
mLbsToKgName:
    .db Sconvert, 'k', 'g', 0
mKgToLbsName:
    .db Sconvert, 'l', 'b', 's', 0
mOzToGName:
    .db Sconvert, 'g', 0
mGToOzName:
    .db Sconvert, 'o', 'z', 0
mGalToLName:
    .db Sconvert, 'L', 0
mLToGalName:
    .db Sconvert, 'g', 'a', 'l', 0
mFlozToMlName:
    .db Sconvert, 'm', 'L', 0
mMlToFlozName:
    .db Sconvert, 'f', 'o', 'z', 0
mCalToKjName:
    .db Sconvert, 'k', 'J', 0
mKjToCalName:
    .db Sconvert, 'c', 'a', 'l', 0
mHpToKwName:
    .db Sconvert, 'k', 'W', 0
mKwToHpName:
    .db Sconvert, 'h', 'p', 0
mClearXName:
    .db "CLX", 0
mClearStackName:
    .db "CLST", 0
mClearRegsName:
    .db "CLRG", 0
mClearStatName:
    .db 'C', 'L', ScapSigma, 0
mFixName:
    .db "FIX", 0
mFixAltName:
    .db 'F', 'I', 'X', Sblock, 0
mSciName:
    .db "SCI", 0
mSciAltName:
    .db 'S', 'C', 'I', Sblock, 0
mEngName:
    .db "ENG", 0
mEngAltName:
    .db 'E', 'N', 'G', Sblock, 0
mRadName:
    .db "RAD", 0
mRadAltName:
    .db 'R', 'A', 'D', Sblock, 0
mDegName:
    .db "DEG", 0
mDegAltName:
    .db 'D', 'E', 'G', Sblock, 0
mStackRotUpName:
    .db 'R', SupArrow, 0
mStackRotDownName:
    .db 'R', SdownArrow, 0
mStackExchangeXYName:
    .db 'X', Sleft, Sconvert, 'Y', 0
