;-----------------------------------------------------------------------------
; Menu hierarchy definitions, generated from menudef.txt.
; See menu.asm for the equivalent C struct declaration.
;
; The following symbols are reserved and pre-generated by the compilemenu.py
; script:
;   - mNull
;   - mNullId
;   - mNullName
;   - mNullNameId
;   - mNullHandler
;
; The following symbols are not reserved, but the root menu group is
; recommended to use the 'mRoot' label, which then generates the following
; for the root menu group:
;   - mRoot
;   - mRootId
;   - mRootNameId
;
; The following is the recommended configuration of the 'GroupHandler'
; directive inside a 'MenuConfig':
;   - GroupHandler mGroupHandler
;
; The following are the recommended configurations for a blank menu item:
;   - ItemName mNullName
;   - ItemNameId mNullNameId
;   - ItemHandler mNullHandler
;
; DO NOT EDIT: This file was autogenerated.
;-----------------------------------------------------------------------------

mMenuTable:
mNull:
mNullId equ 0
    .db mNullId ; id
    .db mNullId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId
    .dw mNullHandler
    .dw 0
mRoot:
mRootId equ 1
    .db mRootId ; id
    .db mNullId ; parentId
    .db mRootNameId ; nameId
    .db 3 ; numRows
    .db mMathId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup root: children
; MenuGroup root: children: row 0
mMath:
mMathId equ 2
    .db mMathId ; id
    .db mRootId ; parentId
    .db mMathNameId ; nameId
    .db 2 ; numRows
    .db mCubeId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mNum:
mNumId equ 3
    .db mNumId ; id
    .db mRootId ; parentId
    .db mNumNameId ; nameId
    .db 3 ; numRows
    .db mPercentId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mProb:
mProbId equ 4
    .db mProbId ; id
    .db mRootId ; parentId
    .db mProbNameId ; nameId
    .db 1 ; numRows
    .db mCombId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mConv:
mConvId equ 5
    .db mConvId ; id
    .db mRootId ; parentId
    .db mConvNameId ; nameId
    .db 2 ; numRows
    .db mRToDId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mHelp:
mHelpId equ 6
    .db mHelpId ; id
    .db mRootId ; parentId
    .db mHelpNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mHelpHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup root: children: row 1
mBase:
mBaseId equ 7
    .db mBaseId ; id
    .db mRootId ; parentId
    .db mBaseNameId ; nameId
    .db 4 ; numRows
    .db mDecId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mHyperbolic:
mHyperbolicId equ 8
    .db mHyperbolicId ; id
    .db mRootId ; parentId
    .db mHyperbolicNameId ; nameId
    .db 2 ; numRows
    .db mBlank077Id ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mStat:
mStatId equ 9
    .db mStatId ; id
    .db mRootId ; parentId
    .db mStatNameId ; nameId
    .db 3 ; numRows
    .db mStatPlusId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mUnit:
mUnitId equ 10
    .db mUnitId ; id
    .db mRootId ; parentId
    .db mUnitNameId ; nameId
    .db 6 ; numRows
    .db mFToCId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mBlank011:
mBlank011Id equ 11
    .db mBlank011Id ; id
    .db mRootId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup root: children: row 2
mClear:
mClearId equ 12
    .db mClearId ; id
    .db mRootId ; parentId
    .db mClearNameId ; nameId
    .db 1 ; numRows
    .db mClearXId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mMode:
mModeId equ 13
    .db mModeId ; id
    .db mRootId ; parentId
    .db mModeNameId ; nameId
    .db 1 ; numRows
    .db mFixId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mStack:
mStackId equ 14
    .db mStackId ; id
    .db mRootId ; parentId
    .db mStackNameId ; nameId
    .db 1 ; numRows
    .db mBlank152Id ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
mBlank015:
mBlank015Id equ 15
    .db mBlank015Id ; id
    .db mRootId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mBlank016:
mBlank016Id equ 16
    .db mBlank016Id ; id
    .db mRootId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup MATH: children
; MenuGroup MATH: children: row 0
mCube:
mCubeId equ 17
    .db mCubeId ; id
    .db mMathId ; parentId
    .db mCubeNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCubeHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCubeRoot:
mCubeRootId equ 18
    .db mCubeRootId ; id
    .db mMathId ; parentId
    .db mCubeRootNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCubeRootHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mAtan2:
mAtan2Id equ 19
    .db mAtan2Id ; id
    .db mMathId ; parentId
    .db mAtan2NameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mAtan2Handler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank020:
mBlank020Id equ 20
    .db mBlank020Id ; id
    .db mMathId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mBlank021:
mBlank021Id equ 21
    .db mBlank021Id ; id
    .db mMathId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup MATH: children: row 1
mAlog2:
mAlog2Id equ 22
    .db mAlog2Id ; id
    .db mMathId ; parentId
    .db mAlog2NameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mAlog2Handler ; handler (to be implemented)
    .dw 0 ; nameSelector
mLog2:
mLog2Id equ 23
    .db mLog2Id ; id
    .db mMathId ; parentId
    .db mLog2NameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mLog2Handler ; handler (to be implemented)
    .dw 0 ; nameSelector
mLogBase:
mLogBaseId equ 24
    .db mLogBaseId ; id
    .db mMathId ; parentId
    .db mLogBaseNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mLogBaseHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank025:
mBlank025Id equ 25
    .db mBlank025Id ; id
    .db mMathId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mBlank026:
mBlank026Id equ 26
    .db mBlank026Id ; id
    .db mMathId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup NUM: children
; MenuGroup NUM: children: row 0
mPercent:
mPercentId equ 27
    .db mPercentId ; id
    .db mNumId ; parentId
    .db mPercentNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mPercentHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mPercentChange:
mPercentChangeId equ 28
    .db mPercentChangeId ; id
    .db mNumId ; parentId
    .db mPercentChangeNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mPercentChangeHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mGcd:
mGcdId equ 29
    .db mGcdId ; id
    .db mNumId ; parentId
    .db mGcdNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mGcdHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mLcm:
mLcmId equ 30
    .db mLcmId ; id
    .db mNumId ; parentId
    .db mLcmNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mLcmHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mPrime:
mPrimeId equ 31
    .db mPrimeId ; id
    .db mNumId ; parentId
    .db mPrimeNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mPrimeHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup NUM: children: row 1
mIntPart:
mIntPartId equ 32
    .db mIntPartId ; id
    .db mNumId ; parentId
    .db mIntPartNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mIntPartHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mFracPart:
mFracPartId equ 33
    .db mFracPartId ; id
    .db mNumId ; parentId
    .db mFracPartNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mFracPartHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mFloor:
mFloorId equ 34
    .db mFloorId ; id
    .db mNumId ; parentId
    .db mFloorNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mFloorHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCeil:
mCeilId equ 35
    .db mCeilId ; id
    .db mNumId ; parentId
    .db mCeilNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCeilHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mNear:
mNearId equ 36
    .db mNearId ; id
    .db mNumId ; parentId
    .db mNearNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNearHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup NUM: children: row 2
mAbs:
mAbsId equ 37
    .db mAbsId ; id
    .db mNumId ; parentId
    .db mAbsNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mAbsHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mSign:
mSignId equ 38
    .db mSignId ; id
    .db mNumId ; parentId
    .db mSignNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mSignHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mMod:
mModId equ 39
    .db mModId ; id
    .db mNumId ; parentId
    .db mModNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mModHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mMin:
mMinId equ 40
    .db mMinId ; id
    .db mNumId ; parentId
    .db mMinNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mMinHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mMax:
mMaxId equ 41
    .db mMaxId ; id
    .db mNumId ; parentId
    .db mMaxNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mMaxHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup PROB: children
; MenuGroup PROB: children: row 0
mComb:
mCombId equ 42
    .db mCombId ; id
    .db mProbId ; parentId
    .db mCombNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCombHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mPerm:
mPermId equ 43
    .db mPermId ; id
    .db mProbId ; parentId
    .db mPermNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mPermHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mFactorial:
mFactorialId equ 44
    .db mFactorialId ; id
    .db mProbId ; parentId
    .db mFactorialNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mFactorialHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRandom:
mRandomId equ 45
    .db mRandomId ; id
    .db mProbId ; parentId
    .db mRandomNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRandomHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRandomSeed:
mRandomSeedId equ 46
    .db mRandomSeedId ; id
    .db mProbId ; parentId
    .db mRandomSeedNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRandomSeedHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup CONV: children
; MenuGroup CONV: children: row 0
mRToD:
mRToDId equ 47
    .db mRToDId ; id
    .db mConvId ; parentId
    .db mRToDNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRToDHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mDToR:
mDToRId equ 48
    .db mDToRId ; id
    .db mConvId ; parentId
    .db mDToRNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mDToRHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank049:
mBlank049Id equ 49
    .db mBlank049Id ; id
    .db mConvId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mPToR:
mPToRId equ 50
    .db mPToRId ; id
    .db mConvId ; parentId
    .db mPToRNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mPToRHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRToP:
mRToPId equ 51
    .db mRToPId ; id
    .db mConvId ; parentId
    .db mRToPNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRToPHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup CONV: children: row 1
mHmsToHr:
mHmsToHrId equ 52
    .db mHmsToHrId ; id
    .db mConvId ; parentId
    .db mHmsToHrNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mHmsToHrHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mHrToHms:
mHrToHmsId equ 53
    .db mHrToHmsId ; id
    .db mConvId ; parentId
    .db mHrToHmsNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mHrToHmsHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank054:
mBlank054Id equ 54
    .db mBlank054Id ; id
    .db mConvId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mBlank055:
mBlank055Id equ 55
    .db mBlank055Id ; id
    .db mConvId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mBlank056:
mBlank056Id equ 56
    .db mBlank056Id ; id
    .db mConvId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup BASE: children
; MenuGroup BASE: children: row 0
mDec:
mDecId equ 57
    .db mDecId ; id
    .db mBaseId ; parentId
    .db mDecNameId ; nameId
    .db 0 ; numRows
    .db mDecAltNameId ; rowBeginId or altNameId
    .dw mDecHandler ; handler (to be implemented)
    .dw mDecNameSelector ; nameSelector
mHex:
mHexId equ 58
    .db mHexId ; id
    .db mBaseId ; parentId
    .db mHexNameId ; nameId
    .db 0 ; numRows
    .db mHexAltNameId ; rowBeginId or altNameId
    .dw mHexHandler ; handler (to be implemented)
    .dw mHexNameSelector ; nameSelector
mOct:
mOctId equ 59
    .db mOctId ; id
    .db mBaseId ; parentId
    .db mOctNameId ; nameId
    .db 0 ; numRows
    .db mOctAltNameId ; rowBeginId or altNameId
    .dw mOctHandler ; handler (to be implemented)
    .dw mOctNameSelector ; nameSelector
mBin:
mBinId equ 60
    .db mBinId ; id
    .db mBaseId ; parentId
    .db mBinNameId ; nameId
    .db 0 ; numRows
    .db mBinAltNameId ; rowBeginId or altNameId
    .dw mBinHandler ; handler (to be implemented)
    .dw mBinNameSelector ; nameSelector
mBlank061:
mBlank061Id equ 61
    .db mBlank061Id ; id
    .db mBaseId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup BASE: children: row 1
mBitwiseAnd:
mBitwiseAndId equ 62
    .db mBitwiseAndId ; id
    .db mBaseId ; parentId
    .db mBitwiseAndNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseAndHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseOr:
mBitwiseOrId equ 63
    .db mBitwiseOrId ; id
    .db mBaseId ; parentId
    .db mBitwiseOrNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseOrHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseXor:
mBitwiseXorId equ 64
    .db mBitwiseXorId ; id
    .db mBaseId ; parentId
    .db mBitwiseXorNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseXorHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseNot:
mBitwiseNotId equ 65
    .db mBitwiseNotId ; id
    .db mBaseId ; parentId
    .db mBitwiseNotNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseNotHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseNeg:
mBitwiseNegId equ 66
    .db mBitwiseNegId ; id
    .db mBaseId ; parentId
    .db mBitwiseNegNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseNegHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup BASE: children: row 2
mShiftLeft:
mShiftLeftId equ 67
    .db mShiftLeftId ; id
    .db mBaseId ; parentId
    .db mShiftLeftNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mShiftLeftHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mShiftRight:
mShiftRightId equ 68
    .db mShiftRightId ; id
    .db mBaseId ; parentId
    .db mShiftRightNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mShiftRightHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRotateLeft:
mRotateLeftId equ 69
    .db mRotateLeftId ; id
    .db mBaseId ; parentId
    .db mRotateLeftNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRotateLeftHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mRotateRight:
mRotateRightId equ 70
    .db mRotateRightId ; id
    .db mBaseId ; parentId
    .db mRotateRightNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mRotateRightHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank071:
mBlank071Id equ 71
    .db mBlank071Id ; id
    .db mBaseId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup BASE: children: row 3
mBitwiseAdd:
mBitwiseAddId equ 72
    .db mBitwiseAddId ; id
    .db mBaseId ; parentId
    .db mBitwiseAddNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseAddHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseSubt:
mBitwiseSubtId equ 73
    .db mBitwiseSubtId ; id
    .db mBaseId ; parentId
    .db mBitwiseSubtNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseSubtHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseMult:
mBitwiseMultId equ 74
    .db mBitwiseMultId ; id
    .db mBaseId ; parentId
    .db mBitwiseMultNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseMultHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseDiv:
mBitwiseDivId equ 75
    .db mBitwiseDivId ; id
    .db mBaseId ; parentId
    .db mBitwiseDivNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseDivHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBitwiseDiv2:
mBitwiseDiv2Id equ 76
    .db mBitwiseDiv2Id ; id
    .db mBaseId ; parentId
    .db mBitwiseDiv2NameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mBitwiseDiv2Handler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup HYP: children
; MenuGroup HYP: children: row 0
mBlank077:
mBlank077Id equ 77
    .db mBlank077Id ; id
    .db mHyperbolicId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mSinh:
mSinhId equ 78
    .db mSinhId ; id
    .db mHyperbolicId ; parentId
    .db mSinhNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mSinhHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCosh:
mCoshId equ 79
    .db mCoshId ; id
    .db mHyperbolicId ; parentId
    .db mCoshNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCoshHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mTanh:
mTanhId equ 80
    .db mTanhId ; id
    .db mHyperbolicId ; parentId
    .db mTanhNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mTanhHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank081:
mBlank081Id equ 81
    .db mBlank081Id ; id
    .db mHyperbolicId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup HYP: children: row 1
mBlank082:
mBlank082Id equ 82
    .db mBlank082Id ; id
    .db mHyperbolicId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mAsinh:
mAsinhId equ 83
    .db mAsinhId ; id
    .db mHyperbolicId ; parentId
    .db mAsinhNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mAsinhHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mAcosh:
mAcoshId equ 84
    .db mAcoshId ; id
    .db mHyperbolicId ; parentId
    .db mAcoshNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mAcoshHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mAtanh:
mAtanhId equ 85
    .db mAtanhId ; id
    .db mHyperbolicId ; parentId
    .db mAtanhNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mAtanhHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank086:
mBlank086Id equ 86
    .db mBlank086Id ; id
    .db mHyperbolicId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup STAT: children
; MenuGroup STAT: children: row 0
mStatPlus:
mStatPlusId equ 87
    .db mStatPlusId ; id
    .db mStatId ; parentId
    .db mStatPlusNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatPlusHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatMinus:
mStatMinusId equ 88
    .db mStatMinusId ; id
    .db mStatId ; parentId
    .db mStatMinusNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatMinusHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatAllMode:
mStatAllModeId equ 89
    .db mStatAllModeId ; id
    .db mStatId ; parentId
    .db mStatAllModeNameId ; nameId
    .db 0 ; numRows
    .db mStatAllModeAltNameId ; rowBeginId or altNameId
    .dw mStatAllModeHandler ; handler (to be implemented)
    .dw mStatAllModeNameSelector ; nameSelector
mStatLinearMode:
mStatLinearModeId equ 90
    .db mStatLinearModeId ; id
    .db mStatId ; parentId
    .db mStatLinearModeNameId ; nameId
    .db 0 ; numRows
    .db mStatLinearModeAltNameId ; rowBeginId or altNameId
    .dw mStatLinearModeHandler ; handler (to be implemented)
    .dw mStatLinearModeNameSelector ; nameSelector
mStatClear:
mStatClearId equ 91
    .db mStatClearId ; id
    .db mStatId ; parentId
    .db mStatClearNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatClearHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup STAT: children: row 1
mStatSum:
mStatSumId equ 92
    .db mStatSumId ; id
    .db mStatId ; parentId
    .db mStatSumNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatSumHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatMean:
mStatMeanId equ 93
    .db mStatMeanId ; id
    .db mStatId ; parentId
    .db mStatMeanNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatMeanHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatWeightedMean:
mStatWeightedMeanId equ 94
    .db mStatWeightedMeanId ; id
    .db mStatId ; parentId
    .db mStatWeightedMeanNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatWeightedMeanHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatN:
mStatNId equ 95
    .db mStatNId ; id
    .db mStatId ; parentId
    .db mStatNNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatNHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank096:
mBlank096Id equ 96
    .db mBlank096Id ; id
    .db mStatId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup STAT: children: row 2
mStatSampleSdev:
mStatSampleSdevId equ 97
    .db mStatSampleSdevId ; id
    .db mStatId ; parentId
    .db mStatSampleSdevNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatSampleSdevHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatSampleCov:
mStatSampleCovId equ 98
    .db mStatSampleCovId ; id
    .db mStatId ; parentId
    .db mStatSampleCovNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatSampleCovHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatPopSdev:
mStatPopSdevId equ 99
    .db mStatPopSdevId ; id
    .db mStatId ; parentId
    .db mStatPopSdevNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatPopSdevHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatPopCov:
mStatPopCovId equ 100
    .db mStatPopCovId ; id
    .db mStatId ; parentId
    .db mStatPopCovNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatPopCovHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCfit:
mCfitId equ 101
    .db mCfitId ; id
    .db mStatId ; parentId
    .db mCfitNameId ; nameId
    .db 2 ; numRows
    .db mStatForcastXId ; rowBeginId or altNameId
    .dw mGroupHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup CFIT: children
; MenuGroup CFIT: children: row 0
mStatForcastX:
mStatForcastXId equ 102
    .db mStatForcastXId ; id
    .db mCfitId ; parentId
    .db mStatForcastXNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatForcastXHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatForcastY:
mStatForcastYId equ 103
    .db mStatForcastYId ; id
    .db mCfitId ; parentId
    .db mStatForcastYNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatForcastYHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatSlope:
mStatSlopeId equ 104
    .db mStatSlopeId ; id
    .db mCfitId ; parentId
    .db mStatSlopeNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatSlopeHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatIntercept:
mStatInterceptId equ 105
    .db mStatInterceptId ; id
    .db mCfitId ; parentId
    .db mStatInterceptNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatInterceptHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStatCorrelation:
mStatCorrelationId equ 106
    .db mStatCorrelationId ; id
    .db mCfitId ; parentId
    .db mStatCorrelationNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatCorrelationHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup CFIT: children: row 1
mStatLinearFit:
mStatLinearFitId equ 107
    .db mStatLinearFitId ; id
    .db mCfitId ; parentId
    .db mStatLinearFitNameId ; nameId
    .db 0 ; numRows
    .db mStatLinearFitAltNameId ; rowBeginId or altNameId
    .dw mStatLinearFitHandler ; handler (to be implemented)
    .dw mStatLinearFitNameSelector ; nameSelector
mStatLogFit:
mStatLogFitId equ 108
    .db mStatLogFitId ; id
    .db mCfitId ; parentId
    .db mStatLogFitNameId ; nameId
    .db 0 ; numRows
    .db mStatLogFitAltNameId ; rowBeginId or altNameId
    .dw mStatLogFitHandler ; handler (to be implemented)
    .dw mStatLogFitNameSelector ; nameSelector
mStatExpFit:
mStatExpFitId equ 109
    .db mStatExpFitId ; id
    .db mCfitId ; parentId
    .db mStatExpFitNameId ; nameId
    .db 0 ; numRows
    .db mStatExpFitAltNameId ; rowBeginId or altNameId
    .dw mStatExpFitHandler ; handler (to be implemented)
    .dw mStatExpFitNameSelector ; nameSelector
mStatPowerFit:
mStatPowerFitId equ 110
    .db mStatPowerFitId ; id
    .db mCfitId ; parentId
    .db mStatPowerFitNameId ; nameId
    .db 0 ; numRows
    .db mStatPowerFitAltNameId ; rowBeginId or altNameId
    .dw mStatPowerFitHandler ; handler (to be implemented)
    .dw mStatPowerFitNameSelector ; nameSelector
mStatBestFit:
mStatBestFitId equ 111
    .db mStatBestFitId ; id
    .db mCfitId ; parentId
    .db mStatBestFitNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStatBestFitHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup UNIT: children
; MenuGroup UNIT: children: row 0
mFToC:
mFToCId equ 112
    .db mFToCId ; id
    .db mUnitId ; parentId
    .db mFToCNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mFToCHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCToF:
mCToFId equ 113
    .db mCToFId ; id
    .db mUnitId ; parentId
    .db mCToFNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCToFHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank114:
mBlank114Id equ 114
    .db mBlank114Id ; id
    .db mUnitId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mInhgToHpa:
mInhgToHpaId equ 115
    .db mInhgToHpaId ; id
    .db mUnitId ; parentId
    .db mInhgToHpaNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mInhgToHpaHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mHpaToInhg:
mHpaToInhgId equ 116
    .db mHpaToInhgId ; id
    .db mUnitId ; parentId
    .db mHpaToInhgNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mHpaToInhgHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup UNIT: children: row 1
mMiToKm:
mMiToKmId equ 117
    .db mMiToKmId ; id
    .db mUnitId ; parentId
    .db mMiToKmNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mMiToKmHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mKmToMi:
mKmToMiId equ 118
    .db mKmToMiId ; id
    .db mUnitId ; parentId
    .db mKmToMiNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mKmToMiHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank119:
mBlank119Id equ 119
    .db mBlank119Id ; id
    .db mUnitId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mFtToM:
mFtToMId equ 120
    .db mFtToMId ; id
    .db mUnitId ; parentId
    .db mFtToMNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mFtToMHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mMToFt:
mMToFtId equ 121
    .db mMToFtId ; id
    .db mUnitId ; parentId
    .db mMToFtNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mMToFtHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup UNIT: children: row 2
mInToCm:
mInToCmId equ 122
    .db mInToCmId ; id
    .db mUnitId ; parentId
    .db mInToCmNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mInToCmHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mCmToIn:
mCmToInId equ 123
    .db mCmToInId ; id
    .db mUnitId ; parentId
    .db mCmToInNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCmToInHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank124:
mBlank124Id equ 124
    .db mBlank124Id ; id
    .db mUnitId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mMilToMicron:
mMilToMicronId equ 125
    .db mMilToMicronId ; id
    .db mUnitId ; parentId
    .db mMilToMicronNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mMilToMicronHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mMicronToMil:
mMicronToMilId equ 126
    .db mMicronToMilId ; id
    .db mUnitId ; parentId
    .db mMicronToMilNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mMicronToMilHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup UNIT: children: row 3
mLbsToKg:
mLbsToKgId equ 127
    .db mLbsToKgId ; id
    .db mUnitId ; parentId
    .db mLbsToKgNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mLbsToKgHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mKgToLbs:
mKgToLbsId equ 128
    .db mKgToLbsId ; id
    .db mUnitId ; parentId
    .db mKgToLbsNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mKgToLbsHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank129:
mBlank129Id equ 129
    .db mBlank129Id ; id
    .db mUnitId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mOzToG:
mOzToGId equ 130
    .db mOzToGId ; id
    .db mUnitId ; parentId
    .db mOzToGNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mOzToGHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mGToOz:
mGToOzId equ 131
    .db mGToOzId ; id
    .db mUnitId ; parentId
    .db mGToOzNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mGToOzHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup UNIT: children: row 4
mGalToL:
mGalToLId equ 132
    .db mGalToLId ; id
    .db mUnitId ; parentId
    .db mGalToLNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mGalToLHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mLToGal:
mLToGalId equ 133
    .db mLToGalId ; id
    .db mUnitId ; parentId
    .db mLToGalNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mLToGalHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank134:
mBlank134Id equ 134
    .db mBlank134Id ; id
    .db mUnitId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mFlozToMl:
mFlozToMlId equ 135
    .db mFlozToMlId ; id
    .db mUnitId ; parentId
    .db mFlozToMlNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mFlozToMlHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mMlToFloz:
mMlToFlozId equ 136
    .db mMlToFlozId ; id
    .db mUnitId ; parentId
    .db mMlToFlozNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mMlToFlozHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup UNIT: children: row 5
mCalToKj:
mCalToKjId equ 137
    .db mCalToKjId ; id
    .db mUnitId ; parentId
    .db mCalToKjNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mCalToKjHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mKjToCal:
mKjToCalId equ 138
    .db mKjToCalId ; id
    .db mUnitId ; parentId
    .db mKjToCalNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mKjToCalHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank139:
mBlank139Id equ 139
    .db mBlank139Id ; id
    .db mUnitId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mHpToKw:
mHpToKwId equ 140
    .db mHpToKwId ; id
    .db mUnitId ; parentId
    .db mHpToKwNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mHpToKwHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mKwToHp:
mKwToHpId equ 141
    .db mKwToHpId ; id
    .db mUnitId ; parentId
    .db mKwToHpNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mKwToHpHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
; MenuGroup CLR: children
; MenuGroup CLR: children: row 0
mClearX:
mClearXId equ 142
    .db mClearXId ; id
    .db mClearId ; parentId
    .db mClearXNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mClearXHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mClearStack:
mClearStackId equ 143
    .db mClearStackId ; id
    .db mClearId ; parentId
    .db mClearStackNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mClearStackHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mClearRegs:
mClearRegsId equ 144
    .db mClearRegsId ; id
    .db mClearId ; parentId
    .db mClearRegsNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mClearRegsHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mClearStat:
mClearStatId equ 145
    .db mClearStatId ; id
    .db mClearId ; parentId
    .db mClearStatNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mClearStatHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank146:
mBlank146Id equ 146
    .db mBlank146Id ; id
    .db mClearId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
; MenuGroup MODE: children
; MenuGroup MODE: children: row 0
mFix:
mFixId equ 147
    .db mFixId ; id
    .db mModeId ; parentId
    .db mFixNameId ; nameId
    .db 0 ; numRows
    .db mFixAltNameId ; rowBeginId or altNameId
    .dw mFixHandler ; handler (to be implemented)
    .dw mFixNameSelector ; nameSelector
mSci:
mSciId equ 148
    .db mSciId ; id
    .db mModeId ; parentId
    .db mSciNameId ; nameId
    .db 0 ; numRows
    .db mSciAltNameId ; rowBeginId or altNameId
    .dw mSciHandler ; handler (to be implemented)
    .dw mSciNameSelector ; nameSelector
mEng:
mEngId equ 149
    .db mEngId ; id
    .db mModeId ; parentId
    .db mEngNameId ; nameId
    .db 0 ; numRows
    .db mEngAltNameId ; rowBeginId or altNameId
    .dw mEngHandler ; handler (to be implemented)
    .dw mEngNameSelector ; nameSelector
mRad:
mRadId equ 150
    .db mRadId ; id
    .db mModeId ; parentId
    .db mRadNameId ; nameId
    .db 0 ; numRows
    .db mRadAltNameId ; rowBeginId or altNameId
    .dw mRadHandler ; handler (to be implemented)
    .dw mRadNameSelector ; nameSelector
mDeg:
mDegId equ 151
    .db mDegId ; id
    .db mModeId ; parentId
    .db mDegNameId ; nameId
    .db 0 ; numRows
    .db mDegAltNameId ; rowBeginId or altNameId
    .dw mDegHandler ; handler (to be implemented)
    .dw mDegNameSelector ; nameSelector
; MenuGroup STK: children
; MenuGroup STK: children: row 0
mBlank152:
mBlank152Id equ 152
    .db mBlank152Id ; id
    .db mStackId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector
mStackRotUp:
mStackRotUpId equ 153
    .db mStackRotUpId ; id
    .db mStackId ; parentId
    .db mStackRotUpNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStackRotUpHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStackRotDown:
mStackRotDownId equ 154
    .db mStackRotDownId ; id
    .db mStackId ; parentId
    .db mStackRotDownNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStackRotDownHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mStackExchangeXY:
mStackExchangeXYId equ 155
    .db mStackExchangeXYId ; id
    .db mStackId ; parentId
    .db mStackExchangeXYNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mStackExchangeXYHandler ; handler (to be implemented)
    .dw 0 ; nameSelector
mBlank156:
mBlank156Id equ 156
    .db mBlank156Id ; id
    .db mStackId ; parentId
    .db mNullNameId ; nameId
    .db 0 ; numRows
    .db 0 ; rowBeginId or altNameId
    .dw mNullHandler ; handler (predefined)
    .dw 0 ; nameSelector

; Table of 2-byte pointers to names in the pool of strings below.
mMenuNameTable:
mNullNameId equ 0
    .dw mNullName
mRootNameId equ 1
    .dw mRootName
mMathNameId equ 2
    .dw mMathName
mNumNameId equ 3
    .dw mNumName
mProbNameId equ 4
    .dw mProbName
mConvNameId equ 5
    .dw mConvName
mHelpNameId equ 6
    .dw mHelpName
mBaseNameId equ 7
    .dw mBaseName
mHyperbolicNameId equ 8
    .dw mHyperbolicName
mStatNameId equ 9
    .dw mStatName
mUnitNameId equ 10
    .dw mUnitName
mClearNameId equ 11
    .dw mClearName
mModeNameId equ 12
    .dw mModeName
mStackNameId equ 13
    .dw mStackName
mCubeNameId equ 14
    .dw mCubeName
mCubeRootNameId equ 15
    .dw mCubeRootName
mAtan2NameId equ 16
    .dw mAtan2Name
mAlog2NameId equ 17
    .dw mAlog2Name
mLog2NameId equ 18
    .dw mLog2Name
mLogBaseNameId equ 19
    .dw mLogBaseName
mPercentNameId equ 20
    .dw mPercentName
mPercentChangeNameId equ 21
    .dw mPercentChangeName
mGcdNameId equ 22
    .dw mGcdName
mLcmNameId equ 23
    .dw mLcmName
mPrimeNameId equ 24
    .dw mPrimeName
mIntPartNameId equ 25
    .dw mIntPartName
mFracPartNameId equ 26
    .dw mFracPartName
mFloorNameId equ 27
    .dw mFloorName
mCeilNameId equ 28
    .dw mCeilName
mNearNameId equ 29
    .dw mNearName
mAbsNameId equ 30
    .dw mAbsName
mSignNameId equ 31
    .dw mSignName
mModNameId equ 32
    .dw mModName
mMinNameId equ 33
    .dw mMinName
mMaxNameId equ 34
    .dw mMaxName
mCombNameId equ 35
    .dw mCombName
mPermNameId equ 36
    .dw mPermName
mFactorialNameId equ 37
    .dw mFactorialName
mRandomNameId equ 38
    .dw mRandomName
mRandomSeedNameId equ 39
    .dw mRandomSeedName
mRToDNameId equ 40
    .dw mRToDName
mDToRNameId equ 41
    .dw mDToRName
mPToRNameId equ 42
    .dw mPToRName
mRToPNameId equ 43
    .dw mRToPName
mHmsToHrNameId equ 44
    .dw mHmsToHrName
mHrToHmsNameId equ 45
    .dw mHrToHmsName
mDecNameId equ 46
    .dw mDecName
mDecAltNameId equ 47
    .dw mDecAltName
mHexNameId equ 48
    .dw mHexName
mHexAltNameId equ 49
    .dw mHexAltName
mOctNameId equ 50
    .dw mOctName
mOctAltNameId equ 51
    .dw mOctAltName
mBinNameId equ 52
    .dw mBinName
mBinAltNameId equ 53
    .dw mBinAltName
mBitwiseAndNameId equ 54
    .dw mBitwiseAndName
mBitwiseOrNameId equ 55
    .dw mBitwiseOrName
mBitwiseXorNameId equ 56
    .dw mBitwiseXorName
mBitwiseNotNameId equ 57
    .dw mBitwiseNotName
mBitwiseNegNameId equ 58
    .dw mBitwiseNegName
mShiftLeftNameId equ 59
    .dw mShiftLeftName
mShiftRightNameId equ 60
    .dw mShiftRightName
mRotateLeftNameId equ 61
    .dw mRotateLeftName
mRotateRightNameId equ 62
    .dw mRotateRightName
mBitwiseAddNameId equ 63
    .dw mBitwiseAddName
mBitwiseSubtNameId equ 64
    .dw mBitwiseSubtName
mBitwiseMultNameId equ 65
    .dw mBitwiseMultName
mBitwiseDivNameId equ 66
    .dw mBitwiseDivName
mBitwiseDiv2NameId equ 67
    .dw mBitwiseDiv2Name
mSinhNameId equ 68
    .dw mSinhName
mCoshNameId equ 69
    .dw mCoshName
mTanhNameId equ 70
    .dw mTanhName
mAsinhNameId equ 71
    .dw mAsinhName
mAcoshNameId equ 72
    .dw mAcoshName
mAtanhNameId equ 73
    .dw mAtanhName
mStatPlusNameId equ 74
    .dw mStatPlusName
mStatMinusNameId equ 75
    .dw mStatMinusName
mStatAllModeNameId equ 76
    .dw mStatAllModeName
mStatAllModeAltNameId equ 77
    .dw mStatAllModeAltName
mStatLinearModeNameId equ 78
    .dw mStatLinearModeName
mStatLinearModeAltNameId equ 79
    .dw mStatLinearModeAltName
mStatClearNameId equ 80
    .dw mStatClearName
mStatSumNameId equ 81
    .dw mStatSumName
mStatMeanNameId equ 82
    .dw mStatMeanName
mStatWeightedMeanNameId equ 83
    .dw mStatWeightedMeanName
mStatNNameId equ 84
    .dw mStatNName
mStatSampleSdevNameId equ 85
    .dw mStatSampleSdevName
mStatSampleCovNameId equ 86
    .dw mStatSampleCovName
mStatPopSdevNameId equ 87
    .dw mStatPopSdevName
mStatPopCovNameId equ 88
    .dw mStatPopCovName
mCfitNameId equ 89
    .dw mCfitName
mStatForcastXNameId equ 90
    .dw mStatForcastXName
mStatForcastYNameId equ 91
    .dw mStatForcastYName
mStatSlopeNameId equ 92
    .dw mStatSlopeName
mStatInterceptNameId equ 93
    .dw mStatInterceptName
mStatCorrelationNameId equ 94
    .dw mStatCorrelationName
mStatLinearFitNameId equ 95
    .dw mStatLinearFitName
mStatLinearFitAltNameId equ 96
    .dw mStatLinearFitAltName
mStatLogFitNameId equ 97
    .dw mStatLogFitName
mStatLogFitAltNameId equ 98
    .dw mStatLogFitAltName
mStatExpFitNameId equ 99
    .dw mStatExpFitName
mStatExpFitAltNameId equ 100
    .dw mStatExpFitAltName
mStatPowerFitNameId equ 101
    .dw mStatPowerFitName
mStatPowerFitAltNameId equ 102
    .dw mStatPowerFitAltName
mStatBestFitNameId equ 103
    .dw mStatBestFitName
mFToCNameId equ 104
    .dw mFToCName
mCToFNameId equ 105
    .dw mCToFName
mInhgToHpaNameId equ 106
    .dw mInhgToHpaName
mHpaToInhgNameId equ 107
    .dw mHpaToInhgName
mMiToKmNameId equ 108
    .dw mMiToKmName
mKmToMiNameId equ 109
    .dw mKmToMiName
mFtToMNameId equ 110
    .dw mFtToMName
mMToFtNameId equ 111
    .dw mMToFtName
mInToCmNameId equ 112
    .dw mInToCmName
mCmToInNameId equ 113
    .dw mCmToInName
mMilToMicronNameId equ 114
    .dw mMilToMicronName
mMicronToMilNameId equ 115
    .dw mMicronToMilName
mLbsToKgNameId equ 116
    .dw mLbsToKgName
mKgToLbsNameId equ 117
    .dw mKgToLbsName
mOzToGNameId equ 118
    .dw mOzToGName
mGToOzNameId equ 119
    .dw mGToOzName
mGalToLNameId equ 120
    .dw mGalToLName
mLToGalNameId equ 121
    .dw mLToGalName
mFlozToMlNameId equ 122
    .dw mFlozToMlName
mMlToFlozNameId equ 123
    .dw mMlToFlozName
mCalToKjNameId equ 124
    .dw mCalToKjName
mKjToCalNameId equ 125
    .dw mKjToCalName
mHpToKwNameId equ 126
    .dw mHpToKwName
mKwToHpNameId equ 127
    .dw mKwToHpName
mClearXNameId equ 128
    .dw mClearXName
mClearStackNameId equ 129
    .dw mClearStackName
mClearRegsNameId equ 130
    .dw mClearRegsName
mClearStatNameId equ 131
    .dw mClearStatName
mFixNameId equ 132
    .dw mFixName
mFixAltNameId equ 133
    .dw mFixAltName
mSciNameId equ 134
    .dw mSciName
mSciAltNameId equ 135
    .dw mSciAltName
mEngNameId equ 136
    .dw mEngName
mEngAltNameId equ 137
    .dw mEngAltName
mRadNameId equ 138
    .dw mRadName
mRadAltNameId equ 139
    .dw mRadAltName
mDegNameId equ 140
    .dw mDegName
mDegAltNameId equ 141
    .dw mDegAltName
mStackRotUpNameId equ 142
    .dw mStackRotUpName
mStackRotDownNameId equ 143
    .dw mStackRotDownName
mStackExchangeXYNameId equ 144
    .dw mStackExchangeXYName

; Table of names as NUL terminated C strings.
mNullName:
    .db 0
mRootName:
    .db "root", 0
mMathName:
    .db "MATH", 0
mNumName:
    .db "NUM", 0
mProbName:
    .db "PROB", 0
mConvName:
    .db "CONV", 0
mHelpName:
    .db "HELP", 0
mBaseName:
    .db "BASE", 0
mHyperbolicName:
    .db "HYP", 0
mStatName:
    .db "STAT", 0
mUnitName:
    .db "UNIT", 0
mClearName:
    .db "CLR", 0
mModeName:
    .db "MODE", 0
mStackName:
    .db "STK", 0
mCubeName:
    .db 'X', Scaret, '3', 0
mCubeRootName:
    .db ScubeR, Sroot, 'X', 0
mAtan2Name:
    .db "ATN2", 0
mAlog2Name:
    .db '2', Scaret, 'X', 0
mLog2Name:
    .db "LOG2", 0
mLogBaseName:
    .db "LOGB", 0
mPercentName:
    .db Spercent, 0
mPercentChangeName:
    .db Spercent, 'C', 'H', 0
mGcdName:
    .db "GCD", 0
mLcmName:
    .db "LCM", 0
mPrimeName:
    .db "PRIM", 0
mIntPartName:
    .db "IP", 0
mFracPartName:
    .db "FP", 0
mFloorName:
    .db "FLR", 0
mCeilName:
    .db "CEIL", 0
mNearName:
    .db "NEAR", 0
mAbsName:
    .db "ABS", 0
mSignName:
    .db "SIGN", 0
mModName:
    .db "MOD", 0
mMinName:
    .db "MIN", 0
mMaxName:
    .db "MAX", 0
mCombName:
    .db "COMB", 0
mPermName:
    .db "PERM", 0
mFactorialName:
    .db 'N', Sexclam, 0
mRandomName:
    .db "RAND", 0
mRandomSeedName:
    .db "SEED", 0
mRToDName:
    .db Sconvert, 'D', 'E', 'G', 0
mDToRName:
    .db Sconvert, 'R', 'A', 'D', 0
mPToRName:
    .db 'P', Sconvert, 'R', 0
mRToPName:
    .db 'R', Sconvert, 'P', 0
mHmsToHrName:
    .db Sconvert, 'H', 'R', 0
mHrToHmsName:
    .db Sconvert, 'H', 'M', 'S', 0
mDecName:
    .db "DEC", 0
mDecAltName:
    .db 'D', 'E', 'C', Sblock, 0
mHexName:
    .db "HEX", 0
mHexAltName:
    .db 'H', 'E', 'X', Sblock, 0
mOctName:
    .db "OCT", 0
mOctAltName:
    .db 'O', 'C', 'T', Sblock, 0
mBinName:
    .db "BIN", 0
mBinAltName:
    .db 'B', 'I', 'N', Sblock, 0
mBitwiseAndName:
    .db "AND", 0
mBitwiseOrName:
    .db "OR", 0
mBitwiseXorName:
    .db "XOR", 0
mBitwiseNotName:
    .db "NOT", 0
mBitwiseNegName:
    .db "NEG", 0
mShiftLeftName:
    .db "SL", 0
mShiftRightName:
    .db "SR", 0
mRotateLeftName:
    .db "RL", 0
mRotateRightName:
    .db "RR", 0
mBitwiseAddName:
    .db 'B', SplusSign, 0
mBitwiseSubtName:
    .db 'B', Sdash, 0
mBitwiseMultName:
    .db 'B', Scross, 0
mBitwiseDivName:
    .db 'B', Sslash, 0
mBitwiseDiv2Name:
    .db "BDIV", 0
mSinhName:
    .db "SINH", 0
mCoshName:
    .db "COSH", 0
mTanhName:
    .db "TANH", 0
mAsinhName:
    .db "ASNH", 0
mAcoshName:
    .db "ACSH", 0
mAtanhName:
    .db "ATNH", 0
mStatPlusName:
    .db ScapSigma, SplusSign, 0
mStatMinusName:
    .db ScapSigma, Sdash, 0
mStatAllModeName:
    .db 'A', 'L', 'L', ScapSigma, 0
mStatAllModeAltName:
    .db 'A', 'L', 'L', Sblock, 0
mStatLinearModeName:
    .db 'L', 'I', 'N', ScapSigma, 0
mStatLinearModeAltName:
    .db 'L', 'I', 'N', Sblock, 0
mStatClearName:
    .db 'C', 'L', ScapSigma, 0
mStatSumName:
    .db "SUM", 0
mStatMeanName:
    .db "MEAN", 0
mStatWeightedMeanName:
    .db "WMN", 0
mStatNName:
    .db "N", 0
mStatSampleSdevName:
    .db "SDEV", 0
mStatSampleCovName:
    .db "SCOV", 0
mStatPopSdevName:
    .db "PDEV", 0
mStatPopCovName:
    .db "PCOV", 0
mCfitName:
    .db "CFIT", 0
mStatForcastXName:
    .db 'Y', Sconvert, 'X', 0
mStatForcastYName:
    .db 'X', Sconvert, 'Y', 0
mStatSlopeName:
    .db "SLOP", 0
mStatInterceptName:
    .db "YINT", 0
mStatCorrelationName:
    .db "CORR", 0
mStatLinearFitName:
    .db "LINF", 0
mStatLinearFitAltName:
    .db 'L', 'I', 'N', Sblock, 0
mStatLogFitName:
    .db "LOGF", 0
mStatLogFitAltName:
    .db 'L', 'O', 'G', Sblock, 0
mStatExpFitName:
    .db "EXPF", 0
mStatExpFitAltName:
    .db 'E', 'X', 'P', Sblock, 0
mStatPowerFitName:
    .db "PWRF", 0
mStatPowerFitAltName:
    .db 'P', 'W', 'R', Sblock, 0
mStatBestFitName:
    .db "BEST", 0
mFToCName:
    .db Sconvert, Stemp, 'C', 0
mCToFName:
    .db Sconvert, Stemp, 'F', 0
mInhgToHpaName:
    .db Sconvert, 'h', 'P', 'a', 0
mHpaToInhgName:
    .db Sconvert, 'i', 'H', 'g', 0
mMiToKmName:
    .db Sconvert, 'k', 'm', 0
mKmToMiName:
    .db Sconvert, 'm', 'i', 0
mFtToMName:
    .db Sconvert, 'm', 0
mMToFtName:
    .db Sconvert, 'f', 't', 0
mInToCmName:
    .db Sconvert, 'c', 'm', 0
mCmToInName:
    .db Sconvert, 'i', 'n', 0
mMilToMicronName:
    .db Sconvert, Smu, 'm', 0
mMicronToMilName:
    .db Sconvert, 'm', 'i', 'l', 0
mLbsToKgName:
    .db Sconvert, 'k', 'g', 0
mKgToLbsName:
    .db Sconvert, 'l', 'b', 's', 0
mOzToGName:
    .db Sconvert, 'g', 0
mGToOzName:
    .db Sconvert, 'o', 'z', 0
mGalToLName:
    .db Sconvert, 'L', 0
mLToGalName:
    .db Sconvert, 'g', 'a', 'l', 0
mFlozToMlName:
    .db Sconvert, 'm', 'L', 0
mMlToFlozName:
    .db Sconvert, 'f', 'o', 'z', 0
mCalToKjName:
    .db Sconvert, 'k', 'J', 0
mKjToCalName:
    .db Sconvert, 'c', 'a', 'l', 0
mHpToKwName:
    .db Sconvert, 'k', 'W', 0
mKwToHpName:
    .db Sconvert, 'h', 'p', 0
mClearXName:
    .db "CLX", 0
mClearStackName:
    .db "CLST", 0
mClearRegsName:
    .db "CLRG", 0
mClearStatName:
    .db 'C', 'L', ScapSigma, 0
mFixName:
    .db "FIX", 0
mFixAltName:
    .db 'F', 'I', 'X', Sblock, 0
mSciName:
    .db "SCI", 0
mSciAltName:
    .db 'S', 'C', 'I', Sblock, 0
mEngName:
    .db "ENG", 0
mEngAltName:
    .db 'E', 'N', 'G', Sblock, 0
mRadName:
    .db "RAD", 0
mRadAltName:
    .db 'R', 'A', 'D', Sblock, 0
mDegName:
    .db "DEG", 0
mDegAltName:
    .db 'D', 'E', 'G', Sblock, 0
mStackRotUpName:
    .db 'R', SupArrow, 0
mStackRotDownName:
    .db 'R', SdownArrow, 0
mStackExchangeXYName:
    .db 'X', Sleft, Sconvert, 'Y', 0
