;-----------------------------------------------------------------------------
; Unit definitions, generated from unitdef.txt.
; See unit2.asm for the equivalent C struct declaration.
;
; There are 3 sections:
;   - list of unit classes
;   - list of units
;   - list of unit names
;
; DO NOT EDIT: This file was autogenerated.
;-----------------------------------------------------------------------------

;-----------------------------------------------------------------------------
; List of UnitClasses
;-----------------------------------------------------------------------------

unitClassLength equ 0
unitClassArea equ 1
unitClassVolume equ 2
unitClassMass equ 3
unitClassTemperature equ 4
unitClassPressure equ 5
unitClassEnergy equ 6
unitClassPower equ 7
unitClassMisc equ 8

;-----------------------------------------------------------------------------
; List of Units
;-----------------------------------------------------------------------------

unitInfoTable:
unitInfoTableSize equ 72

unitAngstromInfo:
unitAngstromId equ 0
    .dw unitAngstromName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $76, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-10
unitNanoMeterInfo:
unitNanoMeterId equ 1
    .dw unitNanoMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $77, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-9
unitMicroMeterInfo:
unitMicroMeterId equ 2
    .dw unitMicroMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $7A, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-6
unitMilliMeterInfo:
unitMilliMeterId equ 3
    .dw unitMilliMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $7D, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-3
unitCentiMeterInfo:
unitCentiMeterId equ 4
    .dw unitCentiMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $7E, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-2
unitMeterInfo:
unitMeterId equ 5
    .dw unitMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1
unitKiloMeterInfo:
unitKiloMeterId equ 6
    .dw unitKiloMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $83, $10, $00, $00, $00, $00, $00, $00 ; scale=1e3
unitMegaMeterInfo:
unitMegaMeterId equ 7
    .dw unitMegaMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $86, $10, $00, $00, $00, $00, $00, $00 ; scale=1e6
unitGigaMeterInfo:
unitGigaMeterId equ 8
    .dw unitGigaMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $89, $10, $00, $00, $00, $00, $00, $00 ; scale=1e9
unitMilInfo:
unitMilId equ 9
    .dw unitMilName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $7B, $25, $40, $00, $00, $00, $00, $00 ; scale=0.0254e-3
unitInchInfo:
unitInchId equ 10
    .dw unitInchName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $7E, $25, $40, $00, $00, $00, $00, $00 ; scale=0.0254
unitFootInfo:
unitFootId equ 11
    .dw unitFootName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $7F, $30, $48, $00, $00, $00, $00, $00 ; scale=0.3048
unitYardInfo:
unitYardId equ 12
    .dw unitYardName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $7F, $91, $44, $00, $00, $00, $00, $00 ; scale=0.9144
unitFanthomInfo:
unitFanthomId equ 13
    .dw unitFanthomName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $80, $18, $28, $80, $00, $00, $00, $00 ; scale=1.8288
unitMileInfo:
unitMileId equ 14
    .dw unitMileName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $83, $16, $09, $34, $40, $00, $00, $00 ; scale=1609.344
unitNauticalMileInfo:
unitNauticalMileId equ 15
    .dw unitNauticalMileName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $83, $18, $52, $00, $00, $00, $00, $00 ; scale=1852
unitAstronomicalUnitInfo:
unitAstronomicalUnitId equ 16
    .dw unitAstronomicalUnitName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $8B, $14, $95, $97, $87, $07, $00, $00 ; scale=149597870700
unitLightYearInfo:
unitLightYearId equ 17
    .dw unitLightYearName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $8F, $94, $60, $73, $04, $72, $58, $08 ; scale=9460730472580.8e3
unitParsecInfo:
unitParsecId equ 18
    .dw unitParsecName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $90, $30, $85, $67, $75, $81, $49, $13 ; scale=30856775814913673
unitMegaParsecInfo:
unitMegaParsecId equ 19
    .dw unitMegaParsecName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $96, $30, $85, $67, $75, $81, $49, $13 ; scale=30856775814913673e6
unitSqMicroMeterInfo:
unitSqMicroMeterId equ 20
    .dw unitSqMicroMeterName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $74, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-12
unitSqMilliMeterInfo:
unitSqMilliMeterId equ 21
    .dw unitSqMilliMeterName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $7A, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-6
unitSqCentiMeterInfo:
unitSqCentiMeterId equ 22
    .dw unitSqCentiMeterName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $7C, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-4
unitSqMeterInfo:
unitSqMeterId equ 23
    .dw unitSqMeterName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1
unitSqKiloMeterInfo:
unitSqKiloMeterId equ 24
    .dw unitSqKiloMeterName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $86, $10, $00, $00, $00, $00, $00, $00 ; scale=1e6
unitSqInchInfo:
unitSqInchId equ 25
    .dw unitSqInchName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $7C, $64, $51, $60, $00, $00, $00, $00 ; scale=6.4516e-4
unitSqFootInfo:
unitSqFootId equ 26
    .dw unitSqFootName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $7E, $92, $90, $30, $40, $00, $00, $00 ; scale=0.09290304
unitSqYardInfo:
unitSqYardId equ 27
    .dw unitSqYardName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $7F, $83, $39, $34, $24, $00, $00, $00 ; scale=0.83393424
unitSqMileInfo:
unitSqMileId equ 28
    .dw unitSqMileName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $86, $25, $89, $98, $81, $10, $33, $60 ; scale=2.589988110336e6
unitSqNauticalMileInfo:
unitSqNauticalMileId equ 29
    .dw unitSqNauticalMileName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $86, $34, $29, $90, $40, $00, $00, $00 ; scale=3429904
unitAcreInfo:
unitAcreId equ 30
    .dw unitAcreName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $83, $40, $46, $85, $64, $22, $40, $00 ; scale=4.0468564224e3
unitHectareInfo:
unitHectareId equ 31
    .dw unitHectareName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $84, $10, $00, $00, $00, $00, $00, $00 ; scale=1e4
unitUSFootballInfo:
unitUSFootballId equ 32
    .dw unitUSFootballName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $83, $44, $59, $34, $59, $20, $00, $00 ; scale=4.45934592e3
unitCAFootballInfo:
unitCAFootballId equ 33
    .dw unitCAFootballName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $83, $59, $78, $31, $06, $24, $00, $00 ; scale=5.978310624e3
unitCuMicroMeterInfo:
unitCuMicroMeterId equ 34
    .dw unitCuMicroMeterName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $6E, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-18
unitCuMilliMeterInfo:
unitCuMilliMeterId equ 35
    .dw unitCuMilliMeterName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $77, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-9
unitCuCentiMeterInfo:
unitCuCentiMeterId equ 36
    .dw unitCuCentiMeterName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7A, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-6
unitCuMeterInfo:
unitCuMeterId equ 37
    .dw unitCuMeterName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1
unitCuKiloMeterInfo:
unitCuKiloMeterId equ 38
    .dw unitCuKiloMeterName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $89, $10, $00, $00, $00, $00, $00, $00 ; scale=1e9
unitCuInchInfo:
unitCuInchId equ 39
    .dw unitCuInchName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7B, $16, $38, $70, $64, $00, $00, $00 ; scale=1.6387064e-5
unitCuFootInfo:
unitCuFootId equ 40
    .dw unitCuFootName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7E, $28, $31, $68, $46, $59, $20, $00 ; scale=2.8316846592e-2
unitCuYardInfo:
unitCuYardId equ 41
    .dw unitCuYardName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7F, $76, $45, $54, $85, $79, $84, $00 ; scale=7.64554857984e-1
unitCuMileInfo:
unitCuMileId equ 42
    .dw unitCuMileName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $89, $41, $68, $18, $18, $25, $44, $06 ; scale=4.1681818254406e9
unitCuNauticalMileInfo:
unitCuNauticalMileId equ 43
    .dw unitCuNauticalMileName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $89, $63, $52, $18, $22, $08, $00, $00 ; scale=6352182208
unitMicroLiterInfo:
unitMicroLiterId equ 44
    .dw unitMicroLiterName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $77, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-9
unitMilliLiterInfo:
unitMilliLiterId equ 45
    .dw unitMilliLiterName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7A, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-6
unitLiterInfo:
unitLiterId equ 46
    .dw unitLiterName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7D, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-3
unitKiloLiterInfo:
unitKiloLiterId equ 47
    .dw unitKiloLiterName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1
unitTeaspoonInfo:
unitTeaspoonId equ 48
    .dw unitTeaspoonName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7A, $49, $28, $92, $15, $93, $75, $00 ; scale=4.92892159375e-6
unitTablespoonInfo:
unitTablespoonId equ 49
    .dw unitTablespoonName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7B, $14, $78, $67, $64, $78, $12, $50 ; scale=1.478676478125e-5
unitFluidOunceInfo:
unitFluidOunceId equ 50
    .dw unitFluidOunceName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7B, $29, $57, $35, $29, $56, $25, $00 ; scale=2.95735295625e-5
unitGillInfo:
unitGillId equ 51
    .dw unitGillName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7C, $11, $82, $94, $11, $82, $50, $00 ; scale=1.1829411825e-4
unitCupInfo:
unitCupId equ 52
    .dw unitCupName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7C, $23, $65, $88, $23, $65, $00, $00 ; scale=2.365882365e-4
unitPintInfo:
unitPintId equ 53
    .dw unitPintName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7C, $47, $31, $76, $47, $30, $00, $00 ; scale=4.73176473e-4
unitQuartInfo:
unitQuartId equ 54
    .dw unitQuartName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7C, $94, $63, $52, $94, $60, $00, $00 ; scale=9.46352946e-4
unitGallonInfo:
unitGallonId equ 55
    .dw unitGallonName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7D, $37, $85, $41, $17, $84, $00, $00 ; scale=3.785411784e-3
unitOilBarrelInfo:
unitOilBarrelId equ 56
    .dw unitOilBarrelName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7F, $15, $89, $87, $29, $49, $28, $00 ; scale=1.58987294928e-1
unitImpFluidOunceInfo:
unitImpFluidOunceId equ 57
    .dw unitImpFluidOunceName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7B, $28, $41, $30, $62, $50, $00, $00 ; scale=2.84130625e-5
unitImpGillInfo:
unitImpGillId equ 58
    .dw unitImpGillName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7C, $14, $20, $65, $31, $25, $00, $00 ; scale=1.420653125e-4
unitImpCupInfo:
unitImpCupId equ 59
    .dw unitImpCupName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7C, $28, $41, $30, $62, $50, $00, $00 ; scale=2.84130625e-4
unitImpPintInfo:
unitImpPintId equ 60
    .dw unitImpPintName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7C, $56, $82, $61, $25, $00, $00, $00 ; scale=5.6826125e-4
unitImpQuartInfo:
unitImpQuartId equ 61
    .dw unitImpQuartName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7D, $11, $36, $52, $25, $00, $00, $00 ; scale=1.1365225e-3
unitImpGallonInfo:
unitImpGallonId equ 62
    .dw unitImpGallonName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7D, $45, $46, $09, $00, $00, $00, $00 ; scale=4.54609e-3
unitOlympicPoolInfo:
unitOlympicPoolId equ 63
    .dw unitOlympicPoolName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $83, $37, $50, $00, $00, $00, $00, $00 ; scale=3750
unitMicroGramInfo:
unitMicroGramId equ 64
    .dw unitMicroGramName ; name
    .db unitClassMass ; unitClass
    .db unitGramId ; baseUnitId
    .db $00, $7A, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-6
unitMilliGramInfo:
unitMilliGramId equ 65
    .dw unitMilliGramName ; name
    .db unitClassMass ; unitClass
    .db unitGramId ; baseUnitId
    .db $00, $7D, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-3
unitGramInfo:
unitGramId equ 66
    .dw unitGramName ; name
    .db unitClassMass ; unitClass
    .db unitGramId ; baseUnitId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1
unitKiloGramInfo:
unitKiloGramId equ 67
    .dw unitKiloGramName ; name
    .db unitClassMass ; unitClass
    .db unitGramId ; baseUnitId
    .db $00, $83, $10, $00, $00, $00, $00, $00, $00 ; scale=1e3
unitMegaGramInfo:
unitMegaGramId equ 68
    .dw unitMegaGramName ; name
    .db unitClassMass ; unitClass
    .db unitGramId ; baseUnitId
    .db $00, $86, $10, $00, $00, $00, $00, $00, $00 ; scale=1e6
unitOunceInfo:
unitOunceId equ 69
    .dw unitOunceName ; name
    .db unitClassMass ; unitClass
    .db unitGramId ; baseUnitId
    .db $00, $81, $28, $34, $95, $23, $12, $50, $00 ; scale=28.349523125
unitPoundInfo:
unitPoundId equ 70
    .dw unitPoundName ; name
    .db unitClassMass ; unitClass
    .db unitGramId ; baseUnitId
    .db $00, $82, $45, $35, $92, $37, $00, $00, $00 ; scale=453.59237
unitTonInfo:
unitTonId equ 71
    .dw unitTonName ; name
    .db unitClassMass ; unitClass
    .db unitGramId ; baseUnitId
    .db $00, $85, $90, $71, $84, $74, $00, $00, $00 ; scale=907.18474e3

;-----------------------------------------------------------------------------
; Unit names.
;-----------------------------------------------------------------------------

unitAngstromName:
    .db "angst", 0
unitNanoMeterName:
    .db "nm", 0
unitMicroMeterName:
    .db Smu, 'm', 0
unitMilliMeterName:
    .db "mm", 0
unitCentiMeterName:
    .db "cm", 0
unitMeterName:
    .db "m", 0
unitKiloMeterName:
    .db "km", 0
unitMegaMeterName:
    .db "Mm", 0
unitGigaMeterName:
    .db "Gm", 0
unitMilName:
    .db "mil", 0
unitInchName:
    .db "in", 0
unitFootName:
    .db "ft", 0
unitYardName:
    .db "yd", 0
unitFanthomName:
    .db "fanthom", 0
unitMileName:
    .db "mi", 0
unitNauticalMileName:
    .db "nmi", 0
unitAstronomicalUnitName:
    .db "AU", 0
unitLightYearName:
    .db "ltyr", 0
unitParsecName:
    .db "pc", 0
unitMegaParsecName:
    .db "Mpc", 0
unitSqMicroMeterName:
    .db Smu, 'm', Sarea, 0
unitSqMilliMeterName:
    .db 'm', 'm', Sarea, 0
unitSqCentiMeterName:
    .db 'c', 'm', Sarea, 0
unitSqMeterName:
    .db 'm', Sarea, 0
unitSqKiloMeterName:
    .db 'm', Sarea, 0
unitSqInchName:
    .db 'i', 'n', Sarea, 0
unitSqFootName:
    .db 'f', 't', Sarea, 0
unitSqYardName:
    .db 'y', 'd', Sarea, 0
unitSqMileName:
    .db 'm', 'i', Sarea, 0
unitSqNauticalMileName:
    .db 'n', 'm', 'i', Sarea, 0
unitAcreName:
    .db "acre", 0
unitHectareName:
    .db "hectare", 0
unitUSFootballName:
    .db "usftball", 0
unitCAFootballName:
    .db "caftball", 0
unitCuMicroMeterName:
    .db Smu, 'm', Scube, 0
unitCuMilliMeterName:
    .db 'm', 'm', Scube, 0
unitCuCentiMeterName:
    .db 'c', 'm', Scube, 0
unitCuMeterName:
    .db 'm', Scube, 0
unitCuKiloMeterName:
    .db 'k', 'm', Scube, 0
unitCuInchName:
    .db 'i', 'n', Scube, 0
unitCuFootName:
    .db 'f', 't', Scube, 0
unitCuYardName:
    .db 'y', 'd', Scube, 0
unitCuMileName:
    .db 'm', 'i', Scube, 0
unitCuNauticalMileName:
    .db 'n', 'm', 'i', Scube, 0
unitMicroLiterName:
    .db Smu, 'L', 0
unitMilliLiterName:
    .db "mL", 0
unitLiterName:
    .db "L", 0
unitKiloLiterName:
    .db "kL", 0
unitTeaspoonName:
    .db "tsp", 0
unitTablespoonName:
    .db "tbsp", 0
unitFluidOunceName:
    .db "floz", 0
unitGillName:
    .db "gill", 0
unitCupName:
    .db "cup", 0
unitPintName:
    .db "pint", 0
unitQuartName:
    .db "quart", 0
unitGallonName:
    .db "gal", 0
unitOilBarrelName:
    .db "barrel", 0
unitImpFluidOunceName:
    .db "impfloz", 0
unitImpGillName:
    .db "impgill", 0
unitImpCupName:
    .db "impcup", 0
unitImpPintName:
    .db "imppint", 0
unitImpQuartName:
    .db "impquart", 0
unitImpGallonName:
    .db "impgal", 0
unitOlympicPoolName:
    .db "olympool", 0
unitMicroGramName:
    .db Smu, 'g', 0
unitMilliGramName:
    .db Smu, 'g', 0
unitGramName:
    .db "g", 0
unitKiloGramName:
    .db "kg", 0
unitMegaGramName:
    .db "Mg", 0
unitOunceName:
    .db "oz", 0
unitPoundName:
    .db "lbs", 0
unitTonName:
    .db "ton", 0
