;-----------------------------------------------------------------------------
; Unit definitions, generated from unitdef.txt.
; See unit2.asm for the equivalent C struct declaration.
;
; There are 3 sections:
;   - list of unit classes
;   - list of units
;   - list of unit names
;
; DO NOT EDIT: This file was autogenerated.
;-----------------------------------------------------------------------------

;-----------------------------------------------------------------------------
; List of UnitClasses
;-----------------------------------------------------------------------------

unitClassLength equ 0
unitClassArea equ 1
unitClassVolume equ 2
unitClassMass equ 3
unitClassTemperature equ 4
unitClassPressure equ 5
unitClassEnergy equ 6
unitClassPower equ 7
unitClassMisc equ 8

;-----------------------------------------------------------------------------
; List of Units
;-----------------------------------------------------------------------------

unitInfoTable:
unitInfoTableSize equ 32

unitNanoMeterInfo:
unitNanoMeterId equ 0
    .dw unitNanoMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $77, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-9
unitMicroMeterInfo:
unitMicroMeterId equ 1
    .dw unitMicroMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $7A, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-6
unitMilliMeterInfo:
unitMilliMeterId equ 2
    .dw unitMilliMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $7D, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-3
unitCentiMeterInfo:
unitCentiMeterId equ 3
    .dw unitCentiMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $7E, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-2
unitMeterInfo:
unitMeterId equ 4
    .dw unitMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1
unitKiloMeterInfo:
unitKiloMeterId equ 5
    .dw unitKiloMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $83, $10, $00, $00, $00, $00, $00, $00 ; scale=1e3
unitMegaMeterInfo:
unitMegaMeterId equ 6
    .dw unitMegaMeterName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $86, $10, $00, $00, $00, $00, $00, $00 ; scale=1e6
unitMilInfo:
unitMilId equ 7
    .dw unitMilName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $7B, $25, $40, $00, $00, $00, $00, $00 ; scale=0.0254e-3
unitInchInfo:
unitInchId equ 8
    .dw unitInchName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $7E, $25, $40, $00, $00, $00, $00, $00 ; scale=0.0254
unitFootInfo:
unitFootId equ 9
    .dw unitFootName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $7F, $30, $48, $00, $00, $00, $00, $00 ; scale=0.3048
unitYardInfo:
unitYardId equ 10
    .dw unitYardName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $7F, $91, $44, $00, $00, $00, $00, $00 ; scale=0.9144
unitFanthomInfo:
unitFanthomId equ 11
    .dw unitFanthomName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $80, $18, $28, $80, $00, $00, $00, $00 ; scale=1.8288
unitMileInfo:
unitMileId equ 12
    .dw unitMileName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $83, $16, $09, $34, $40, $00, $00, $00 ; scale=1609.344
unitNauticalMileInfo:
unitNauticalMileId equ 13
    .dw unitNauticalMileName ; name
    .db unitClassLength ; unitClass
    .db unitMeterId ; baseUnitId
    .db $00, $83, $18, $52, $00, $00, $00, $00, $00 ; scale=1852
unitSqMilliMeterInfo:
unitSqMilliMeterId equ 14
    .dw unitSqMilliMeterName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $7A, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-6
unitSqCentiMeterInfo:
unitSqCentiMeterId equ 15
    .dw unitSqCentiMeterName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $7C, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-4
unitSqMeterInfo:
unitSqMeterId equ 16
    .dw unitSqMeterName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1
unitSqKiloMeterInfo:
unitSqKiloMeterId equ 17
    .dw unitSqKiloMeterName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $86, $10, $00, $00, $00, $00, $00, $00 ; scale=1e6
unitSqInchInfo:
unitSqInchId equ 18
    .dw unitSqInchName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $7C, $64, $51, $60, $00, $00, $00, $00 ; scale=6.4516e-4
unitSqFootInfo:
unitSqFootId equ 19
    .dw unitSqFootName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $7E, $92, $90, $30, $40, $00, $00, $00 ; scale=0.09290304
unitSqYardInfo:
unitSqYardId equ 20
    .dw unitSqYardName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $7F, $83, $39, $34, $24, $00, $00, $00 ; scale=0.83393424
unitSqMileInfo:
unitSqMileId equ 21
    .dw unitSqMileName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $86, $25, $89, $98, $81, $10, $33, $60 ; scale=2.589988110336e6
unitSqNauticalMileInfo:
unitSqNauticalMileId equ 22
    .dw unitSqNauticalMileName ; name
    .db unitClassArea ; unitClass
    .db unitSqMeterId ; baseUnitId
    .db $00, $86, $34, $29, $90, $40, $00, $00, $00 ; scale=3429904
unitCuMilliMeterInfo:
unitCuMilliMeterId equ 23
    .dw unitCuMilliMeterName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $77, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-9
unitCuCentiMeterInfo:
unitCuCentiMeterId equ 24
    .dw unitCuCentiMeterName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7A, $10, $00, $00, $00, $00, $00, $00 ; scale=1e-6
unitCuMeterInfo:
unitCuMeterId equ 25
    .dw unitCuMeterName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $80, $10, $00, $00, $00, $00, $00, $00 ; scale=1
unitCuKiloMeterInfo:
unitCuKiloMeterId equ 26
    .dw unitCuKiloMeterName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $89, $10, $00, $00, $00, $00, $00, $00 ; scale=1e9
unitCuInchInfo:
unitCuInchId equ 27
    .dw unitCuInchName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7B, $16, $38, $70, $64, $00, $00, $00 ; scale=1.6387064e-5
unitCuFootInfo:
unitCuFootId equ 28
    .dw unitCuFootName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7E, $28, $31, $68, $46, $59, $20, $00 ; scale=2.8316846592e-2
unitCuYardInfo:
unitCuYardId equ 29
    .dw unitCuYardName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $7F, $76, $45, $54, $85, $79, $84, $00 ; scale=7.64554857984e-1
unitCuMileInfo:
unitCuMileId equ 30
    .dw unitCuMileName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $89, $41, $68, $18, $18, $25, $44, $06 ; scale=4.1681818254406e9
unitCuNauticalMileInfo:
unitCuNauticalMileId equ 31
    .dw unitCuNauticalMileName ; name
    .db unitClassVolume ; unitClass
    .db unitCuMeterId ; baseUnitId
    .db $00, $89, $63, $52, $18, $22, $08, $00, $00 ; scale=6352182208

;-----------------------------------------------------------------------------
; Unit names.
;-----------------------------------------------------------------------------

unitNanoMeterName:
    .db "nm", 0
unitMicroMeterName:
    .db Smu, 'm', 0
unitMilliMeterName:
    .db "mm", 0
unitCentiMeterName:
    .db "cm", 0
unitMeterName:
    .db "m", 0
unitKiloMeterName:
    .db "km", 0
unitMegaMeterName:
    .db "Mm", 0
unitMilName:
    .db "mil", 0
unitInchName:
    .db "in", 0
unitFootName:
    .db "ft", 0
unitYardName:
    .db "yd", 0
unitFanthomName:
    .db "fanthom", 0
unitMileName:
    .db "mi", 0
unitNauticalMileName:
    .db "nmi", 0
unitSqMilliMeterName:
    .db 'm', 'm', Scaret, '2', 0
unitSqCentiMeterName:
    .db 'c', 'm', Scaret, '2', 0
unitSqMeterName:
    .db 'm', Scaret, '2', 0
unitSqKiloMeterName:
    .db 'm', Scaret, '2', 0
unitSqInchName:
    .db 'i', 'n', Scaret, '2', 0
unitSqFootName:
    .db 'f', 't', Scaret, '2', 0
unitSqYardName:
    .db 'y', 'd', Scaret, '2', 0
unitSqMileName:
    .db 'm', 'i', Scaret, '2', 0
unitSqNauticalMileName:
    .db 'n', 'm', 'i', Scaret, '2', 0
unitCuMilliMeterName:
    .db 'm', 'm', Scaret, '3', 0
unitCuCentiMeterName:
    .db 'c', 'm', Scaret, '3', 0
unitCuMeterName:
    .db 'm', Scaret, '3', 0
unitCuKiloMeterName:
    .db 'k', 'm', Scaret, '3', 0
unitCuInchName:
    .db 'i', 'n', Scaret, '3', 0
unitCuFootName:
    .db 'f', 't', Scaret, '3', 0
unitCuYardName:
    .db 'y', 'd', Scaret, '3', 0
unitCuMileName:
    .db 'm', 'i', Scaret, '3', 0
unitCuNauticalMileName:
    .db 'n', 'm', 'i', Scaret, '3', 0
